<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Patricio Pantaleo">
<meta name="description" content="Este estudio analiza el ecosistema de revistas académicas chilenas que utilizan Open Journal Systems (OJS) basándose en el dataset PKP Beacon v5 como fuente principal. Se procesaron 316 instalaciones chilenas activas (criterio >5 publicaciones/2023) de un total de 403 instalaciones identificadas en Chile. El análisis incluye referencias contextuales al Beacon v6 (noviembre 2024) que reporta 86,282 instalaciones OJS globales y 432 instalaciones chilenas.La metodología integra cuatro fuentes de datos aplicadas al dataset depurado v5: PKP Beacon para caracterización editorial base, Dialnet para evaluación de calidad editorial mediante 95 informes procesados, OpenAlex para métricas de visibilidad académica, y Crossref para análisis de cobertura de metadatos. Se generaron 208 URLs OAI únicas evaluables e identificaron 40 tipos de errores en prácticas editoriales.Los hallazgos revelan: (1) heterogeneidad significativa en estándares de metadatos y prácticas editoriales, (2) oportunidades de mejora en indexación internacional y preservación digital, y (3) necesidad de fortalecimiento en interoperabilidad y visibilidad académica. El estudio establece una línea base metodológica replicable para evaluación de ecosistemas editoriales regionales y proporciona datos cuantitativos para políticas de fortalecimiento del sector académico chileno.">

<title>Calidad editorial y prácticas de metadatos en revistas académicas chilenas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4aee1ec9d9906071d278d84a676c7a6f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/Ppantaleo/Informes-Bibliometricos/tree/main/OJSinTheWorld/Chile"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text">GitHub</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Calidad editorial y prácticas de metadatos en revistas académicas chilenas</h1>
            <p class="subtitle lead">Un análisis de instalaciones OJS mediante informes de calidad Dialnet, Open Alex y Crossref</p>
                  <div>
        <div class="description">
          <p>Este estudio analiza el ecosistema de revistas académicas chilenas que utilizan Open Journal Systems (OJS) basándose en el dataset PKP Beacon v5 como fuente principal. Se procesaron <strong>316 instalaciones chilenas activas</strong> (criterio &gt;5 publicaciones/2023) de un total de <strong>403 instalaciones identificadas</strong> en Chile. El análisis incluye referencias contextuales al Beacon v6 (noviembre 2024) que reporta <strong>86,282 instalaciones OJS globales</strong> y <strong>432 instalaciones chilenas</strong>.</p>
          <p>La metodología integra cuatro fuentes de datos aplicadas al dataset depurado v5: <strong>PKP Beacon</strong> para caracterización editorial base, <strong>Dialnet</strong> para evaluación de calidad editorial mediante <strong>95 informes procesados</strong>, <strong>OpenAlex</strong> para métricas de visibilidad académica, y <strong>Crossref</strong> para análisis de cobertura de metadatos. Se generaron <strong>208 URLs OAI únicas</strong> evaluables e identificaron <strong>40 tipos de errores</strong> en prácticas editoriales.</p>
          <p>Los hallazgos revelan: (1) <strong>heterogeneidad significativa</strong> en estándares de metadatos y prácticas editoriales, (2) <strong>oportunidades de mejora</strong> en indexación internacional y preservación digital, y (3) <strong>necesidad de fortalecimiento</strong> en interoperabilidad y visibilidad académica. El estudio establece una <strong>línea base metodológica</strong> replicable para evaluación de ecosistemas editoriales regionales y proporciona datos cuantitativos para políticas de fortalecimiento del sector académico chileno.</p>
        </div>
      </div>
                </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Autor/a</div>
      <div class="quarto-title-meta-contents">
               <p>Patricio Pantaleo </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Fecha de publicación</div>
      <div class="quarto-title-meta-contents">
        <p class="date">24 de noviembre de 2025</p>
      </div>
    </div>
    
      
      <div>
      <div class="quarto-title-meta-heading">Doi</div>
      <div class="quarto-title-meta-contents">
        <p class="doi">
          <a href="https://doi.org/10.62059/7k8p45">10.62059/7k8p45</a>
        </p>
      </div>
    </div>
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">1. Introducción</a>
  <ul>
  <li><a href="#contexto" id="toc-contexto" class="nav-link" data-scroll-target="#contexto">1.1 Contexto</a></li>
  <li><a href="#problemática" id="toc-problemática" class="nav-link" data-scroll-target="#problemática">1.2 Problemática</a></li>
  <li><a href="#antecedentes-y-marco-conceptual" id="toc-antecedentes-y-marco-conceptual" class="nav-link" data-scroll-target="#antecedentes-y-marco-conceptual">1.3 Antecedentes y marco conceptual</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos">1.4 Objetivos</a>
  <ul class="collapse">
  <li><a href="#objetivo-general" id="toc-objetivo-general" class="nav-link" data-scroll-target="#objetivo-general">1.4.1 Objetivo general</a></li>
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos">1.4.2 Objetivos específicos</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#materiales-y-métodos" id="toc-materiales-y-métodos" class="nav-link" data-scroll-target="#materiales-y-métodos">2. Materiales y métodos</a>
  <ul>
  <li><a href="#fuente-de-datos" id="toc-fuente-de-datos" class="nav-link" data-scroll-target="#fuente-de-datos">2.1 Fuente de datos</a>
  <ul class="collapse">
  <li><a href="#dataset-pkp-beacon-v5-versión-inicial" id="toc-dataset-pkp-beacon-v5-versión-inicial" class="nav-link" data-scroll-target="#dataset-pkp-beacon-v5-versión-inicial">2.1.1 Dataset PKP Beacon v5 (versión inicial)</a></li>
  <li><a href="#dataset-principal-pkp-beacon-v6" id="toc-dataset-principal-pkp-beacon-v6" class="nav-link" data-scroll-target="#dataset-principal-pkp-beacon-v6">2.1.2 Dataset principal PKP Beacon v6</a></li>
  <li><a href="#dialnet---sistema-de-evaluación-de-calidad-editorial" id="toc-dialnet---sistema-de-evaluación-de-calidad-editorial" class="nav-link" data-scroll-target="#dialnet---sistema-de-evaluación-de-calidad-editorial">2.1.3 Dialnet - sistema de evaluación de calidad editorial</a></li>
  <li><a href="#openalex---base-de-datos-de-visibilidad-académica" id="toc-openalex---base-de-datos-de-visibilidad-académica" class="nav-link" data-scroll-target="#openalex---base-de-datos-de-visibilidad-académica">2.1.4 OpenAlex - base de datos de visibilidad académica</a></li>
  <li><a href="#crossref---infraestructura-de-metadatos-y-dois" id="toc-crossref---infraestructura-de-metadatos-y-dois" class="nav-link" data-scroll-target="#crossref---infraestructura-de-metadatos-y-dois">2.1.5 Crossref - infraestructura de metadatos y DOIs</a></li>
  </ul></li>
  <li><a href="#metodología-de-análisis" id="toc-metodología-de-análisis" class="nav-link" data-scroll-target="#metodología-de-análisis">2.2 Metodología de análisis</a>
  <ul class="collapse">
  <li><a href="#flujo-metodológico-v5-versión-inicial" id="toc-flujo-metodológico-v5-versión-inicial" class="nav-link" data-scroll-target="#flujo-metodológico-v5-versión-inicial">2.2.1 Flujo metodológico v5 (versión inicial)</a></li>
  <li><a href="#flujo-metodológico-v6-validación-actualizada" id="toc-flujo-metodológico-v6-validación-actualizada" class="nav-link" data-scroll-target="#flujo-metodológico-v6-validación-actualizada">2.2.2 Flujo metodológico v6 (validación actualizada)</a></li>
  <li><a href="#decisión-metodológica-continuidad-operativa-v5" id="toc-decisión-metodológica-continuidad-operativa-v5" class="nav-link" data-scroll-target="#decisión-metodológica-continuidad-operativa-v5">2.2.3 Decisión metodológica: continuidad operativa v5</a></li>
  <li><a href="#metodología-de-enriquecimiento-openalex" id="toc-metodología-de-enriquecimiento-openalex" class="nav-link" data-scroll-target="#metodología-de-enriquecimiento-openalex">2.2.4 Metodología de enriquecimiento OpenAlex</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#resultados" id="toc-resultados" class="nav-link" data-scroll-target="#resultados">3. Resultados</a>
  <ul>
  <li><a href="#análisis-global" id="toc-análisis-global" class="nav-link" data-scroll-target="#análisis-global">3.1 Análisis global</a>
  <ul class="collapse">
  <li><a href="#ecosistema-global-v5-línea-base" id="toc-ecosistema-global-v5-línea-base" class="nav-link" data-scroll-target="#ecosistema-global-v5-línea-base">3.1.1 Ecosistema global v5 (línea base)</a></li>
  <li><a href="#ecosistema-global-v6-validación-actualizada" id="toc-ecosistema-global-v6-validación-actualizada" class="nav-link" data-scroll-target="#ecosistema-global-v6-validación-actualizada">3.1.2 Ecosistema global v6 (validación actualizada)</a></li>
  <li><a href="#comparación-global-v5-vs-v6" id="toc-comparación-global-v5-vs-v6" class="nav-link" data-scroll-target="#comparación-global-v5-vs-v6">3.1.3 Comparación global v5 vs v6</a></li>
  </ul></li>
  <li><a href="#análisis-específico-de-chile" id="toc-análisis-específico-de-chile" class="nav-link" data-scroll-target="#análisis-específico-de-chile">3.2 Análisis específico de Chile</a>
  <ul class="collapse">
  <li><a href="#ecosistema-chileno-v5-dataset-principal" id="toc-ecosistema-chileno-v5-dataset-principal" class="nav-link" data-scroll-target="#ecosistema-chileno-v5-dataset-principal">3.2.1 Ecosistema chileno v5 (dataset principal)</a></li>
  <li><a href="#ecosistema-chileno-v6-validación-actualizada" id="toc-ecosistema-chileno-v6-validación-actualizada" class="nav-link" data-scroll-target="#ecosistema-chileno-v6-validación-actualizada">3.2.2 Ecosistema chileno v6 (validación actualizada)</a></li>
  <li><a href="#validación-v6-análisis-de-crecimiento-2023-2024" id="toc-validación-v6-análisis-de-crecimiento-2023-2024" class="nav-link" data-scroll-target="#validación-v6-análisis-de-crecimiento-2023-2024">3.2.7 Validación v6: análisis de crecimiento 2023-2024</a></li>
  <li><a href="#comparación-chile-v5-vs-v6" id="toc-comparación-chile-v5-vs-v6" class="nav-link" data-scroll-target="#comparación-chile-v5-vs-v6">3.2.3 Comparación Chile v5 vs v6</a></li>
  </ul></li>
  <li><a href="#análisis-de-calidad-editorial-informes-dialnet" id="toc-análisis-de-calidad-editorial-informes-dialnet" class="nav-link" data-scroll-target="#análisis-de-calidad-editorial-informes-dialnet">3.3 Análisis de calidad editorial: informes Dialnet</a>
  <ul class="collapse">
  <li><a href="#procesamiento-de-informes" id="toc-procesamiento-de-informes" class="nav-link" data-scroll-target="#procesamiento-de-informes">3.3.1 Procesamiento de informes</a></li>
  <li><a href="#resultados-de-calidad-editorial" id="toc-resultados-de-calidad-editorial" class="nav-link" data-scroll-target="#resultados-de-calidad-editorial">3.3.2 Resultados de calidad editorial</a></li>
  <li><a href="#revistas-con-mayor-número-de-errores" id="toc-revistas-con-mayor-número-de-errores" class="nav-link" data-scroll-target="#revistas-con-mayor-número-de-errores">3.3.3 Revistas con mayor número de errores</a></li>
  <li><a href="#completitud-de-metadatos" id="toc-completitud-de-metadatos" class="nav-link" data-scroll-target="#completitud-de-metadatos">3.3.4 Completitud de metadatos</a></li>
  <li><a href="#análisis-de-tipos-de-errores-por-gravedad" id="toc-análisis-de-tipos-de-errores-por-gravedad" class="nav-link" data-scroll-target="#análisis-de-tipos-de-errores-por-gravedad">3.3.5 Análisis de tipos de errores por gravedad</a></li>
  <li><a href="#implicaciones-para-indexación" id="toc-implicaciones-para-indexación" class="nav-link" data-scroll-target="#implicaciones-para-indexación">3.3.6 Implicaciones para indexación</a></li>
  </ul></li>
  <li><a href="#análisis-de-visibilidad-académica-integración-openalex" id="toc-análisis-de-visibilidad-académica-integración-openalex" class="nav-link" data-scroll-target="#análisis-de-visibilidad-académica-integración-openalex">3.4 Análisis de visibilidad académica: integración OpenAlex</a>
  <ul class="collapse">
  <li><a href="#resultados-de-visibilidad-global" id="toc-resultados-de-visibilidad-global" class="nav-link" data-scroll-target="#resultados-de-visibilidad-global">3.4.1 Resultados de visibilidad global</a></li>
  <li><a href="#análisis-preliminar-chile-script-11" id="toc-análisis-preliminar-chile-script-11" class="nav-link" data-scroll-target="#análisis-preliminar-chile-script-11">3.4.2 Análisis preliminar Chile (Script 11)</a></li>
  <li><a href="#análisis-estratégico-de-visibilidad-script-12" id="toc-análisis-estratégico-de-visibilidad-script-12" class="nav-link" data-scroll-target="#análisis-estratégico-de-visibilidad-script-12">3.4.3 Análisis estratégico de visibilidad (Script 12)</a></li>
  <li><a href="#implicaciones-para-estrategia-de-indexación" id="toc-implicaciones-para-estrategia-de-indexación" class="nav-link" data-scroll-target="#implicaciones-para-estrategia-de-indexación">3.4.4 Implicaciones para estrategia de indexación</a></li>
  <li><a href="#análisis-openalex-ampliado-para-revistas-chilenas-activas-resultados-definitivos" id="toc-análisis-openalex-ampliado-para-revistas-chilenas-activas-resultados-definitivos" class="nav-link" data-scroll-target="#análisis-openalex-ampliado-para-revistas-chilenas-activas-resultados-definitivos">3.4.5 Análisis OpenAlex ampliado para revistas chilenas activas (RESULTADOS DEFINITIVOS)</a></li>
  </ul></li>
  <li><a href="#análisis-de-crossref---revistas-chilenas-activas" id="toc-análisis-de-crossref---revistas-chilenas-activas" class="nav-link" data-scroll-target="#análisis-de-crossref---revistas-chilenas-activas">3.5 Análisis de Crossref - revistas chilenas activas</a>
  <ul class="collapse">
  <li><a href="#cobertura-en-crossref" id="toc-cobertura-en-crossref" class="nav-link" data-scroll-target="#cobertura-en-crossref">3.5.1 Cobertura en Crossref</a></li>
  <li><a href="#distribución-de-dois-registrados" id="toc-distribución-de-dois-registrados" class="nav-link" data-scroll-target="#distribución-de-dois-registrados">3.5.2 Distribución de DOIs registrados</a></li>
  <li><a href="#cobertura-de-metadatos" id="toc-cobertura-de-metadatos" class="nav-link" data-scroll-target="#cobertura-de-metadatos">3.5.3 Cobertura de metadatos</a></li>
  <li><a href="#top-10-revistas-por-dois-en-crossref" id="toc-top-10-revistas-por-dois-en-crossref" class="nav-link" data-scroll-target="#top-10-revistas-por-dois-en-crossref">3.5.4 Top 10 revistas por DOIs en Crossref</a></li>
  <li><a href="#relaciones-de-versiones-y-preprints" id="toc-relaciones-de-versiones-y-preprints" class="nav-link" data-scroll-target="#relaciones-de-versiones-y-preprints">3.5.5 Relaciones de versiones y preprints</a></li>
  <li><a href="#observaciones-clave-crossref" id="toc-observaciones-clave-crossref" class="nav-link" data-scroll-target="#observaciones-clave-crossref">3.5.6 Observaciones clave Crossref</a></li>
  </ul></li>
  <li><a href="#análisis-comparativo-cruzado-integración-de-tres-fuentes" id="toc-análisis-comparativo-cruzado-integración-de-tres-fuentes" class="nav-link" data-scroll-target="#análisis-comparativo-cruzado-integración-de-tres-fuentes">3.6 Análisis comparativo cruzado: integración de tres fuentes</a>
  <ul class="collapse">
  <li><a href="#metodología-de-integración-script-15" id="toc-metodología-de-integración-script-15" class="nav-link" data-scroll-target="#metodología-de-integración-script-15">3.6.1 Metodología de integración (Script 15)</a></li>
  <li><a href="#segmentación-estratégica" id="toc-segmentación-estratégica" class="nav-link" data-scroll-target="#segmentación-estratégica">3.6.2 Segmentación estratégica</a></li>
  <li><a href="#top-10-revistas-por-potencial-combinado" id="toc-top-10-revistas-por-potencial-combinado" class="nav-link" data-scroll-target="#top-10-revistas-por-potencial-combinado">3.6.3 Top 10 revistas por potencial combinado</a></li>
  <li><a href="#correlaciones-clave-identificadas" id="toc-correlaciones-clave-identificadas" class="nav-link" data-scroll-target="#correlaciones-clave-identificadas">3.6.4 Correlaciones clave identificadas</a></li>
  <li><a href="#recomendaciones-por-segmento" id="toc-recomendaciones-por-segmento" class="nav-link" data-scroll-target="#recomendaciones-por-segmento">3.6.5 Recomendaciones por segmento</a></li>
  <li><a href="#análisis-apc-vs-revistas-gratuitas-script-16" id="toc-análisis-apc-vs-revistas-gratuitas-script-16" class="nav-link" data-scroll-target="#análisis-apc-vs-revistas-gratuitas-script-16">3.6.6 Análisis APC vs revistas gratuitas (Script 16)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#discusión" id="toc-discusión" class="nav-link" data-scroll-target="#discusión">4. Discusión</a>
  <ul>
  <li><a href="#validación-del-ecosistema-global" id="toc-validación-del-ecosistema-global" class="nav-link" data-scroll-target="#validación-del-ecosistema-global">4.1 Validación del ecosistema global</a></li>
  <li><a href="#caracterización-del-ecosistema-chileno-actualizada" id="toc-caracterización-del-ecosistema-chileno-actualizada" class="nav-link" data-scroll-target="#caracterización-del-ecosistema-chileno-actualizada">4.2 Caracterización del ecosistema chileno actualizada</a>
  <ul class="collapse">
  <li><a href="#fortalezas-confirmadas-v6" id="toc-fortalezas-confirmadas-v6" class="nav-link" data-scroll-target="#fortalezas-confirmadas-v6">4.2.1 Fortalezas confirmadas v6</a></li>
  <li><a href="#tendencias-identificadas" id="toc-tendencias-identificadas" class="nav-link" data-scroll-target="#tendencias-identificadas">4.2.2 Tendencias identificadas</a></li>
  </ul></li>
  <li><a href="#análisis-comparativo-cruzado-nuevas-perspectivas" id="toc-análisis-comparativo-cruzado-nuevas-perspectivas" class="nav-link" data-scroll-target="#análisis-comparativo-cruzado-nuevas-perspectivas">4.3 Análisis comparativo cruzado: nuevas perspectivas</a>
  <ul class="collapse">
  <li><a href="#integración-exitosa-de-tres-fuentes" id="toc-integración-exitosa-de-tres-fuentes" class="nav-link" data-scroll-target="#integración-exitosa-de-tres-fuentes">4.3.1 Integración exitosa de tres fuentes</a></li>
  <li><a href="#segmentación-estratégica-validada" id="toc-segmentación-estratégica-validada" class="nav-link" data-scroll-target="#segmentación-estratégica-validada">4.3.2 Segmentación estratégica validada</a></li>
  <li><a href="#modelo-de-financiamiento-sostenible" id="toc-modelo-de-financiamiento-sostenible" class="nav-link" data-scroll-target="#modelo-de-financiamiento-sostenible">4.3.3 Modelo de financiamiento sostenible</a></li>
  </ul></li>
  <li><a href="#implicaciones-para-indexación-en-dialnet" id="toc-implicaciones-para-indexación-en-dialnet" class="nav-link" data-scroll-target="#implicaciones-para-indexación-en-dialnet">4.4 Implicaciones para indexación en Dialnet</a>
  <ul class="collapse">
  <li><a href="#optimización-del-proceso" id="toc-optimización-del-proceso" class="nav-link" data-scroll-target="#optimización-del-proceso">4.4.1 Optimización del proceso</a></li>
  <li><a href="#estrategia-de-priorización-actualizada" id="toc-estrategia-de-priorización-actualizada" class="nav-link" data-scroll-target="#estrategia-de-priorización-actualizada">4.4.2 Estrategia de priorización actualizada</a></li>
  </ul></li>
  <li><a href="#contribución-al-acceso-abierto-regional" id="toc-contribución-al-acceso-abierto-regional" class="nav-link" data-scroll-target="#contribución-al-acceso-abierto-regional">4.5 Contribución al acceso abierto regional</a></li>
  <li><a href="#limitaciones-y-consideraciones" id="toc-limitaciones-y-consideraciones" class="nav-link" data-scroll-target="#limitaciones-y-consideraciones">4.6 Limitaciones y consideraciones</a></li>
  </ul></li>
  <li><a href="#limitaciones-del-estudio" id="toc-limitaciones-del-estudio" class="nav-link" data-scroll-target="#limitaciones-del-estudio">5. Limitaciones del estudio</a>
  <ul>
  <li><a href="#limitaciones-metodológicas" id="toc-limitaciones-metodológicas" class="nav-link" data-scroll-target="#limitaciones-metodológicas">5.1 Limitaciones metodológicas</a></li>
  <li><a href="#limitaciones-técnicas" id="toc-limitaciones-técnicas" class="nav-link" data-scroll-target="#limitaciones-técnicas">5.2 Limitaciones técnicas</a></li>
  <li><a href="#limitaciones-de-alcance" id="toc-limitaciones-de-alcance" class="nav-link" data-scroll-target="#limitaciones-de-alcance">5.3 Limitaciones de alcance</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">6. Conclusiones</a>
  <ul>
  <li><a href="#validación-del-ecosistema-robusto" id="toc-validación-del-ecosistema-robusto" class="nav-link" data-scroll-target="#validación-del-ecosistema-robusto">6.1 Validación del ecosistema robusto</a></li>
  <li><a href="#liderazgo-institucional-confirmado" id="toc-liderazgo-institucional-confirmado" class="nav-link" data-scroll-target="#liderazgo-institucional-confirmado">6.2 Liderazgo institucional confirmado</a></li>
  <li><a href="#crecimiento-sostenido-validado" id="toc-crecimiento-sostenido-validado" class="nav-link" data-scroll-target="#crecimiento-sostenido-validado">6.3 Crecimiento sostenido validado</a></li>
  <li><a href="#metodología-consolidada" id="toc-metodología-consolidada" class="nav-link" data-scroll-target="#metodología-consolidada">6.4 Metodología consolidada</a></li>
  <li><a href="#posicionamiento-global" id="toc-posicionamiento-global" class="nav-link" data-scroll-target="#posicionamiento-global">6.5 Posicionamiento global</a></li>
  </ul></li>
  <li><a href="#agradecimientos" id="toc-agradecimientos" class="nav-link" data-scroll-target="#agradecimientos">Agradecimientos</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  <li><a href="#colaboraciones" id="toc-colaboraciones" class="nav-link" data-scroll-target="#colaboraciones">Colaboraciones</a></li>
  <li><a href="#anexos" id="toc-anexos" class="nav-link" data-scroll-target="#anexos">Anexos</a>
  <ul>
  <li><a href="#anexo-a-diccionario-de-datos-del-pkp-beacon" id="toc-anexo-a-diccionario-de-datos-del-pkp-beacon" class="nav-link" data-scroll-target="#anexo-a-diccionario-de-datos-del-pkp-beacon">Anexo A: Diccionario de datos del PKP Beacon</a>
  <ul class="collapse">
  <li><a href="#campos-descriptivos" id="toc-campos-descriptivos" class="nav-link" data-scroll-target="#campos-descriptivos">Campos descriptivos</a></li>
  <li><a href="#campos-de-conteo-y-actividad" id="toc-campos-de-conteo-y-actividad" class="nav-link" data-scroll-target="#campos-de-conteo-y-actividad">Campos de conteo y actividad</a></li>
  </ul></li>
  <li><a href="#anexo-b-scripts-desarrollados" id="toc-anexo-b-scripts-desarrollados" class="nav-link" data-scroll-target="#anexo-b-scripts-desarrollados">Anexo B: Scripts desarrollados</a>
  <ul class="collapse">
  <li><a href="#scripts-de-análisis-general" id="toc-scripts-de-análisis-general" class="nav-link" data-scroll-target="#scripts-de-análisis-general">Scripts de análisis general</a></li>
  <li><a href="#scripts-específicos-de-chile" id="toc-scripts-específicos-de-chile" class="nav-link" data-scroll-target="#scripts-específicos-de-chile">Scripts específicos de Chile</a></li>
  </ul></li>
  <li><a href="#anexo-c-proceso-de-evaluación-en-dialnet" id="toc-anexo-c-proceso-de-evaluación-en-dialnet" class="nav-link" data-scroll-target="#anexo-c-proceso-de-evaluación-en-dialnet">Anexo C: Proceso de evaluación en Dialnet</a>
  <ul class="collapse">
  <li><a href="#estado-actual" id="toc-estado-actual" class="nav-link" data-scroll-target="#estado-actual">Estado actual</a></li>
  <li><a href="#organización-de-informes-descargados" id="toc-organización-de-informes-descargados" class="nav-link" data-scroll-target="#organización-de-informes-descargados">Organización de informes descargados</a></li>
  <li><a href="#registro-de-errores-del-sistema-nexus" id="toc-registro-de-errores-del-sistema-nexus" class="nav-link" data-scroll-target="#registro-de-errores-del-sistema-nexus">Registro de errores del sistema Nexus</a></li>
  <li><a href="#limitaciones-identificadas" id="toc-limitaciones-identificadas" class="nav-link" data-scroll-target="#limitaciones-identificadas">Limitaciones identificadas</a></li>
  <li><a href="#alternativas-evaluadas" id="toc-alternativas-evaluadas" class="nav-link" data-scroll-target="#alternativas-evaluadas">Alternativas evaluadas</a></li>
  </ul></li>
  <li><a href="#anexo-d-reproducibilidad" id="toc-anexo-d-reproducibilidad" class="nav-link" data-scroll-target="#anexo-d-reproducibilidad">Anexo D: Reproducibilidad</a>
  <ul class="collapse">
  <li><a href="#requisitos-del-sistema" id="toc-requisitos-del-sistema" class="nav-link" data-scroll-target="#requisitos-del-sistema">Requisitos del sistema</a></li>
  <li><a href="#repositorio-de-código" id="toc-repositorio-de-código" class="nav-link" data-scroll-target="#repositorio-de-código">Repositorio de código</a></li>
  <li><a href="#estructura-de-archivos-generados" id="toc-estructura-de-archivos-generados" class="nav-link" data-scroll-target="#estructura-de-archivos-generados">Estructura de archivos generados</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Otros formatos</h2><ul><li><a href="Informe.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="Informe.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">1. Introducción</h2>
<section id="contexto" class="level3">
<h3 class="anchored" data-anchor-id="contexto">1.1 Contexto</h3>
<p>El Public Knowledge Project (PKP) desarrolla software de código abierto para la publicación académica, siendo Open Journal Systems (OJS) su aplicación más utilizada globalmente con más de 86,000 instalaciones activas. El PKP Beacon es un sistema de recopilación de datos que permite identificar, inspeccionar y catalogar instalaciones públicas de este software, proporcionando una ventana única para analizar el ecosistema editorial académico mundial.</p>
<p>En el contexto latinoamericano, Chile representa un caso de estudio relevante por su ecosistema editorial diverso y su posición estratégica en la región. Con 432 instalaciones OJS identificadas y 316 activas según criterios DOAJ, Chile concentra aproximadamente el 0.5% del universo global OJS, pero su análisis detallado permite extraer patrones aplicables a otros contextos regionales.</p>
</section>
<section id="problemática" class="level3">
<h3 class="anchored" data-anchor-id="problemática">1.2 Problemática</h3>
<p>La evaluación de calidad editorial en revistas académicas enfrenta desafíos metodológicos significativos, especialmente en ecosistemas como OJS. La heterogeneidad en prácticas de metadatos, estándares de indexación y visibilidad académica genera brechas de información que dificultan la toma de decisiones informadas por parte de editores, investigadores y formuladores de políticas.</p>
<p>Este estudio aborda tres problemáticas centrales: (1) la <strong>falta de caracterización integral</strong> del ecosistema OJS chileno, (2) la <strong>ausencia de metodologías estandarizadas</strong> para evaluación de calidad editorial a escala, y (3) la <strong>limitada integración</strong> entre sistemas de evaluación (Dialnet, OpenAlex, Crossref) que permita análisis comparativos robustos.</p>
</section>
<section id="antecedentes-y-marco-conceptual" class="level3">
<h3 class="anchored" data-anchor-id="antecedentes-y-marco-conceptual">1.3 Antecedentes y marco conceptual</h3>
<p>La investigación sobre el ecosistema editorial basado en Open Journal Systems ha experimentado un desarrollo significativo en los últimos años, consolidando metodologías para el análisis sistemático de instalaciones OJS a escala global. En consonancia con estudios anteriores, se denomina aquí <strong>JUOJS</strong> a las revistas que utilizan OJS <span class="citation" data-cites="alperin2016peripheries khanna2022recalibrating">(<a href="#ref-alperin2016peripheries" role="doc-biblioref">Alperin et&nbsp;al., 2016</a>; <a href="#ref-khanna2022recalibrating" role="doc-biblioref">Khanna et&nbsp;al., 2022</a>)</span>.Las JUOJS emplean un PKP Beacon opcional que permite a PKP notificar sobre actualizaciones y transmite información de indexación incluyendo título, ISSN, número de artículos, entre otros <span class="citation" data-cites="khanna2024details">(<a href="#ref-khanna2024details" role="doc-biblioref">Khanna et&nbsp;al., 2024</a>)</span>.</p>
<p>A partir de dicha caracterización, se emplea el estándar establecido en 2020 por Directory of Open Access Journals (DOAJ) de <strong>cinco artículos al año</strong> para distinguir revistas con actividad editorial sostenida de instalaciones inactivas o en prueba. Este criterio, está establecido en <span class="citation" data-cites="chavarro2025open">Chavarro et&nbsp;al. (<a href="#ref-chavarro2025open" role="doc-biblioref">2025</a>)</span> donde se dice:</p>
<blockquote class="blockquote">
<p>“This study relies on data gathered from the PKP Beacon, a feature introduced into OJS in 2015 that allows PKP to notify OJS users about security updates and software upgrades. The beacon also notifies PKP of the web location of each journal’s metadata harvesting API, which we subsequently used to collect journal metadata, such as the journal name and ISSN, and article metadata, such as titles, abstracts, publication dates, and DOIs. As in our previous study, we considered a journal to be “active” in a given year if it published at least five documents that year, a threshold established by the Directory of Open Access Journal (DOAJ) in 2020. We began with the OJS journal list updated in 2024 (Khanna et al., 2024). This updated list included 50,920 journals with an ISSN, and that were deemed to be active in 2023 (a 98% increase in the number reported for 2020; Khanna et al., 2022).”</p>
</blockquote>
<p>Los estudios sobre JUOJS tienen antecedentes que se remontan a <span class="citation" data-cites="alperin2016peripheries">Alperin et&nbsp;al. (<a href="#ref-alperin2016peripheries" role="doc-biblioref">2016</a>)</span>, quienes localizaron <strong>9,828 revistas</strong> en 2015, estableciendo las primeras estimaciones del ecosistema global. La línea de investigación consolidada por <span class="citation" data-cites="khanna2022recalibrating">Khanna et&nbsp;al. (<a href="#ref-khanna2022recalibrating" role="doc-biblioref">2022</a>)</span> estableció las bases metodológicas para el análisis cuantitativo sistemático, identificando <strong>25,671 revistas activas</strong> de un universo de 70,214 beacons OJS operativos en 2020, representando el 36.5% del total. Este trabajo reveló la magnitud del ecosistema con <strong>996,000 artículos publicados en 2020</strong> y un acervo histórico de <strong>5.4 millones de artículos</strong>, demostrando un crecimiento de <strong>161%</strong> respecto a las estimaciones de 2015 y estableciendo una línea base cuantitativa robusta para estudios comparativos.</p>
<p>La actualización metodológica de <span class="citation" data-cites="chavarro2025open">Chavarro et&nbsp;al. (<a href="#ref-chavarro2025open" role="doc-biblioref">2025</a>)</span> demostró el crecimiento acelerado del ecosistema para el año 2024, identificando <strong>50.920 revistas JUOJS activas</strong>, lo que representó un <strong>aumento del 98% respecto a 2020</strong>. El trabajo de <span class="citation" data-cites="chavarro2025open">Chavarro et&nbsp;al. (<a href="#ref-chavarro2025open" role="doc-biblioref">2025</a>)</span> marca un antecedentes metodológico al integrar datos del PKP Beacon con OpenAlex para evaluar visibilidad e impacto académico. La metodología de <span class="citation" data-cites="chavarro2025open">Chavarro et&nbsp;al. (<a href="#ref-chavarro2025open" role="doc-biblioref">2025</a>)</span> es particularmente relevante para este estudio, ya que establece el marco conceptual para la integración de múltiples fuentes de datos y la evaluación de visibilidad académica en ecosistemas OJS.</p>
<p>La versión más reciente del dataset PKP Beacon (noviembre 2025) proporciona el contexto global actualizado con <strong>86,282 instalaciones OJS globales</strong>, confirmando el crecimiento sostenido del ecosistema, de las cuales <strong>54,453</strong> son revistas JUOJS consideradas activas. Para Chile específicamente, el Beacon v6 identifica <strong>432 instalaciones totales</strong> y <strong>319 instalaciones activas</strong>, validando metodológicamente las tendencias identificadas en versiones anteriores.</p>
</section>
<section id="objetivos" class="level3">
<h3 class="anchored" data-anchor-id="objetivos">1.4 Objetivos</h3>
<p>A pesar de los avances significativos en la caracterización cuantitativa del ecosistema OJS global, persisten brechas importantes en:</p>
<ol type="1">
<li><p><strong>Análisis integrado de calidad editorial</strong>: Los estudios previos se enfocan en métricas de productividad y visibilidad, pero carecen de evaluación sistemática de calidad editorial y prácticas de metadatos.</p></li>
<li><p><strong>Caracterización regional detallada</strong>: Aunque existen datos globales, faltan análisis profundos de ecosistemas nacionales que permitan identificar patrones regionales y oportunidades de mejora.</p></li>
</ol>
<p>Este estudio aborda estas brechas mediante un enfoque metodológico integrado aplicado al caso chileno, estableciendo un modelo replicable para análisis comparativos regionales.</p>
<section id="objetivo-general" class="level4">
<h4 class="anchored" data-anchor-id="objetivo-general">1.4.1 Objetivo general</h4>
<p>Caracterizar el ecosistema editorial académico chileno basado en OJS mediante análisis multifuente que combine evaluación de calidad editorial, visibilidad académica y cobertura de metadatos.</p>
</section>
<section id="objetivos-específicos" class="level4">
<h4 class="anchored" data-anchor-id="objetivos-específicos">1.4.2 Objetivos específicos</h4>
<ol type="1">
<li><strong>Caracterizar cuantitativamente</strong> las 316 instalaciones OJS chilenas activas identificadas en el dataset PKP Beacon v5</li>
<li><strong>Evaluar la calidad editorial</strong> mediante procesamiento sistemático de 95 informes Dialnet, identificando patrones de errores y buenas prácticas</li>
<li><strong>Analizar la visibilidad académica</strong> integrando métricas OpenAlex para evaluar impacto, indexación y acceso abierto</li>
<li><strong>Examinar la cobertura de metadatos</strong> utilizando APIs Crossref para evaluar completitud de DOIs, referencias y afiliaciones</li>
<li><strong>Proponer metodologías replicables</strong> para análisis comparativos de ecosistemas editoriales regionales</li>
<li><strong>Generar recomendaciones</strong> basadas en evidencia para fortalecimiento del sector editorial académico chileno</li>
</ol>
</section>
</section>
</section>
<section id="materiales-y-métodos" class="level2">
<h2 class="anchored" data-anchor-id="materiales-y-métodos">2. Materiales y métodos</h2>
<p>Este estudio implementa una metodología de análisis integrado que combina cuatro fuentes de datos complementarias para caracterizar integralmente el ecosistema editorial académico chileno basado en OJS. La aproximación metodológica se fundamenta en el dataset PKP Beacon v5 como fuente principal, enriquecido con evaluaciones de calidad editorial (Dialnet), métricas de visibilidad académica (OpenAlex) e infraestructura de metadatos (Crossref). Esta integración multifuente permite superar las limitaciones de análisis unidimensionales, proporcionando una visión holística que abarca desde la productividad editorial hasta el impacto académico y la calidad de los estándares editoriales.</p>
<p>La metodología se estructura en dos fases principales: (1) <strong>caracterización cuantitativa</strong> del ecosistema chileno mediante procesamiento sistemático de los datasets PKP Beacon v5 y v6, estableciendo líneas base de productividad y crecimiento; y (2) <strong>enriquecimiento cualitativo</strong> a través de la integración con sistemas especializados de evaluación, permitiendo análisis comparativos y segmentación estratégica de las 316 instalaciones chilenas activas identificadas. El enfoque garantiza reproducibilidad mediante scripts automatizados y establece estándares metodológicos replicables para estudios comparativos regionales.</p>
<section id="fuente-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="fuente-de-datos">2.1 Fuente de datos</h3>
<section id="dataset-pkp-beacon-v5-versión-inicial" class="level4">
<h4 class="anchored" data-anchor-id="dataset-pkp-beacon-v5-versión-inicial">2.1.1 Dataset PKP Beacon v5 (versión inicial)</h4>
<p><strong>Dataset:</strong> <span class="citation" data-cites="khanna2024details">Khanna et&nbsp;al. (<a href="#ref-khanna2024details" role="doc-biblioref">2024</a>)</span></p>
<p><strong>Características v5:</strong></p>
<ul>
<li><strong>DOI:</strong> https://doi.org/10.7910/DVN/OCZNVY</li>
<li><strong>Archivo:</strong> <code>beacon.csv</code> (67,138 observaciones, 25 campos)</li>
<li><strong>Instalaciones OJS:</strong> 66,527 (99.1%)</li>
<li><strong>Instalaciones OMP:</strong> 562 (0.8%)</li>
<li><strong>Instalaciones OPS:</strong> 49 (0.1%)</li>
<li><strong>Datos hasta:</strong> 2023 (último año completo)</li>
<li><strong>Criterio actividad:</strong> &gt;5 publicaciones en 2023</li>
<li><strong>Chile identificado:</strong> 403 instalaciones totales</li>
<li><strong>Chile activas v5:</strong> 316 instalaciones (78.4%)</li>
</ul>
</section>
<section id="dataset-principal-pkp-beacon-v6" class="level4">
<h4 class="anchored" data-anchor-id="dataset-principal-pkp-beacon-v6">2.1.2 Dataset principal PKP Beacon v6</h4>
<p><strong>Dataset:</strong> Khanna, S., Raoni, J., Smecher, A., Alperin, J. P., Ball, J., &amp; Willinsky, J. (2024). “Details of Publications Using Software by the Public Knowledge Project.” Harvard Dataverse.</p>
<p><strong>Características v6:</strong></p>
<ul>
<li><strong>Archivo:</strong> <code>beacon_v6.csv</code> (87,170 observaciones, 31 campos)</li>
<li><strong>Instalaciones OJS:</strong> 86,282 (99.0%)</li>
<li><strong>Instalaciones OMP:</strong> 810 (0.9%)</li>
<li><strong>Instalaciones OPS:</strong> 78 (0.1%)</li>
<li><strong>Nuevas columnas:</strong>
<ul>
<li><code>record_count_2024</code> - Publicaciones 2024</li>
<li><code>record_count_2025</code> - Publicaciones 2025</li>
<li><code>region</code> - Región geográfica PKP</li>
<li><code>admin_email</code> - Email de administrador</li>
<li><code>country_doaj</code> - País según DOAJ</li>
</ul></li>
</ul>
</section>
<section id="dialnet---sistema-de-evaluación-de-calidad-editorial" class="level4">
<h4 class="anchored" data-anchor-id="dialnet---sistema-de-evaluación-de-calidad-editorial">2.1.3 Dialnet - sistema de evaluación de calidad editorial</h4>
<p><strong>Plataforma:</strong> Universidad de La Rioja - Dialnet Nexus <strong>URL:</strong> https://dialnet.unirioja.es/</p>
<p><strong>Características:</strong> - <strong>Sistema de evaluación:</strong> Nexus - Validador automático de calidad editorial - <strong>Protocolo:</strong> OAI-PMH (Open Archives Initiative Protocol for Metadata Harvesting) - <strong>Métricas evaluadas:</strong> Completitud de metadatos, errores de formato, estándares editoriales - <strong>Tipos de errores:</strong> 40 categorías clasificadas por gravedad (alta/media) - <strong>Cobertura Chile:</strong> 95 informes procesados de 208 URLs únicas - <strong>Formato de salida:</strong> Informes HTML con análisis detallado por revista</p>
<p><strong>Limitaciones:</strong> - Proceso manual de solicitud de informes - No disponible API para automatización - Dependiente de configuración correcta de endpoints OAI</p>
</section>
<section id="openalex---base-de-datos-de-visibilidad-académica" class="level4">
<h4 class="anchored" data-anchor-id="openalex---base-de-datos-de-visibilidad-académica">2.1.4 OpenAlex - base de datos de visibilidad académica</h4>
<p><strong>Plataforma:</strong> OpenAlex (OurResearch) <strong>URL:</strong> https://openalex.org/ <strong>API:</strong> https://docs.openalex.org/</p>
<p><strong>Características:</strong> - <strong>Cobertura:</strong> &gt;200 millones de trabajos académicos - <strong>Actualización:</strong> Continua, datos hasta 2024 - <strong>Identificadores:</strong> ISSN, DOI, ORCID, ROR - <strong>Métricas disponibles:</strong> - <code>works_count</code> - Artículos indexados - <code>cited_by_count</code> - Total citaciones - <code>h_index</code> - Índice H de la revista - <code>2yr_mean_citedness</code> - Promedio citaciones 2 años - <code>is_oa</code> - Estado acceso abierto - <code>is_in_doaj</code> - Indexación en DOAJ - <code>apc_usd</code> - Costos de procesamiento (APC)</p>
<p><strong>Cobertura Chile:</strong> - <strong>Revistas procesadas:</strong> 304 de 316 (96.2%) - <strong>Revistas indexadas:</strong> 259 de 304 (85.2%) - <strong>Limitación:</strong> 12 revistas excluidas por falta de ISSN</p>
</section>
<section id="crossref---infraestructura-de-metadatos-y-dois" class="level4">
<h4 class="anchored" data-anchor-id="crossref---infraestructura-de-metadatos-y-dois">2.1.5 Crossref - infraestructura de metadatos y DOIs</h4>
<p><strong>Plataforma:</strong> Crossref <strong>URL:</strong> https://www.crossref.org/ <strong>API:</strong> https://api.crossref.org/</p>
<p><strong>Características:</strong> - <strong>Función:</strong> Registro y gestión de DOIs académicos - <strong>Cobertura global:</strong> &gt;130 millones de registros - <strong>Métricas de metadatos:</strong> - DOIs actuales e históricos - Cobertura de resúmenes, licencias, ORCIDs - Referencias bibliográficas y afiliaciones - Relaciones de versiones y preprints - <strong>Rate limiting:</strong> 0.2s entre requests, timeout 15s</p>
<p><strong>Cobertura Chile:</strong> - <strong>Revistas analizadas:</strong> 316 - <strong>Revistas encontradas:</strong> 256 (81.0%) - <strong>Total DOIs registrados:</strong> 96,754 - DOIs actuales: 15,910 - DOIs históricos: 80,844</p>
<p><strong>Limitaciones identificadas:</strong> - Baja cobertura de referencias (7.9%) - Ausencia de políticas de actualización (0.0%) - No utilización de relaciones de versiones/preprints</p>
</section>
</section>
<section id="metodología-de-análisis" class="level3">
<h3 class="anchored" data-anchor-id="metodología-de-análisis">2.2 Metodología de análisis</h3>
<p>La metodología de análisis se estructura en un flujo secuencial de procesamiento que integra las cuatro fuentes de datos mediante scripts automatizados, garantizando reproducibilidad y trazabilidad de resultados. El enfoque metodológico se fundamenta en dos líneas paralelas: (1) <strong>procesamiento principal</strong> basado en PKP Beacon v5 para análisis detallado y enriquecimiento multifuente, y (2) <strong>validación contextual</strong> mediante PKP Beacon v6 para confirmar tendencias y actualizar estimaciones globales.</p>
<p>El flujo metodológico v5 constituye el <strong>eje central del análisis</strong>, procesando sistemáticamente las 316 instalaciones chilenas activas a través de seis etapas secuenciales: caracterización base, evaluación de calidad editorial (Dialnet), análisis de visibilidad académica (OpenAlex), evaluación de infraestructura de metadatos (Crossref), integración comparativa y segmentación estratégica. Cada etapa genera datasets intermedios que alimentan análisis posteriores, culminando en variables novedosas como <strong>madurez editorial</strong>, <strong>brecha de visibilidad</strong> y <strong>potencial de indexación</strong> que permiten clasificación estratégica de las revistas en cinco segmentos operativos.</p>
<section id="flujo-metodológico-v5-versión-inicial" class="level4">
<h4 class="anchored" data-anchor-id="flujo-metodológico-v5-versión-inicial">2.2.1 Flujo metodológico v5 (versión inicial)</h4>
<p><strong>1. Procesamiento Base v5</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separar beacon por tipo de aplicación</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/1_split_beacon.py</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: beacon_ojs.csv (66,527 instalaciones)</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis global OJS</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts/2_analisis_ojs_mundial.R</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/top15_paises_barras.png</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>2. Análisis Chile v5</strong></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar dataset completo de Chile (todos los criterios de país)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts/3_analisis_chile.R</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/chile_todas_instalaciones.csv (403)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar solo instalaciones activas (&gt;5 pub/2023)</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts/4_chile_juojs_filtrado.R</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/chile_juojs_activas.csv (316 - DATASET PRINCIPAL v5)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>3. Evaluación Dialnet v5</strong></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar URLs OAI desde dataset JUOJS v5</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/5_generar_urls_dialnet.py</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/chile_oai_urls_limpio.csv (209 URLs únicas)</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Se elimina https://journals.publicknowledgeproject.org/index.php/index/oai por ser una reconocida URL test de PKP, quedando 208 URLs únicas.</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sobre este csv se procede a descargar los informes desde https://dialnet.unirioja.es/nexo/o/calidad/solicitar-informe dejando los mensajes de errores cuando los hubo.</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Se modifica output_path = '../visualizations/chile_oai_urls_nuevo.csv' para evitar sobreescrituras en el archivo original en futuras validaciones, ya que el origina fue actualizado manualmente con mensajes de error de Dialnet. </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar completitud de informes descargados</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/6_find_missing_reports.py</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Procesar informes HTML de Dialnet descargados</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/8_procesar_informes_dialnet.py</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/dialnet_informes_procesados.csv</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Analizar tipos de errores por gravedad</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/9_analizar_tipos_errores.py</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: análisis de 40 tipos de errores en 95 informes</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>4. Consulta y Análisis OpenAlex v5</strong></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enriquecer con datos de visibilidad académica OpenAlex</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/10_openalex.py</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/beacon_ojs_con_visibilidad.csv</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar datos de visibilidad para revistas chilenas activas</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/11_filtrar_chile_visibilidad.py</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations/chile_ojs_con_visibilidad.csv</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis estratégico de visibilidad académica</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/12_analisis_estrategico_visibilidad.py</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: 7 archivos CSV con análisis detallados</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Enriquecimiento OpenAlex ampliado para revistas chilenas activas</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/13_openalex_chile_ampliado.py</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: chile_juojs_activas.csv (316 revistas)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: 13_chile_openalex_ampliado.csv + 3 gráficos PNG</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Campos ampliados: is_oa, is_in_doaj, apc_usd, host_organization, i10_index, etc.</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Cobertura mejorada: 85.2% (259/304 revistas) vs 46.8% del Script 11</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Justificación: Consulta directa específica sobre dataset chileno por mayor precisión</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="co"># y acceso a 32 campos ampliados vs metodología indirecta del Script 11</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="co"># NOTA: Este script genera los resultados DEFINITIVOS para el informe</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>5. Consulta y Análisis Crossref v5</strong></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis ampliado de Crossref para revistas chilenas activas</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/14_crossref_chile_ampliado.py</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: chile_juojs_activas.csv (316 revistas)</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: 14_chile_crossref_ampliado.csv + 3 gráficos PNG + tabla MD</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Métricas Crossref: DOIs (actuales/históricos), cobertura metadatos, relaciones versiones</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Campos: current_dois, backfile_dois, abstracts_current/backfile, licenses_current/backfile,</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#         orcids_current/backfile, affiliations_current/backfile, references_current/backfile,</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#         has_preprints, is_preprint_count, has_versions, replacement_relations</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Rate limiting: 0.2s entre requests, timeout 15s, muestra 50 artículos para relaciones</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis comparativo cruzado entre las tres fuentes de datos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>6. Análisis Comparativo</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/15_analisis_comparativo_cruzado.py</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: dialnet_informes_procesados.csv, 13_chile_openalex_ampliado.csv, 14_chile_crossref_ampliado.csv</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: 15_analisis_comparativo_cruzado.csv + visualizaciones PNG</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables novedosas: madurez_editorial, brecha_visibilidad, coherencia_metadatos, potencial_indexacion</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Segmentación estratégica: Estrella, Oportunidad, Problema, Veterana, Básico</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis de correlaciones entre calidad editorial, visibilidad académica y infraestructura DOI</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación revistas con APC vs gratuitas</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/16_comparacion_apc_vs_gratuitas.py</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: 15_analisis_comparativo_cruzado.csv</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: 16_comparacion_apc_vs_gratuitas.png + análisis estadístico</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación: completitud metadatos, visibilidad académica, H-index, distribución por segmentos</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificación: solo 3 revistas chilenas cobran APC (0.9% del total)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="flujo-metodológico-v6-validación-actualizada" class="level4">
<h4 class="anchored" data-anchor-id="flujo-metodológico-v6-validación-actualizada">2.2.2 Flujo metodológico v6 (validación actualizada)</h4>
<p><strong>0. Limpieza de Datos v6 (Preprocesamiento con Comandos)</strong></p>
<p><strong>Problemática identificada:</strong> El archivo <code>beacon_v6.tab</code> original presentaba saltos de línea incrustados dentro de campos de texto que rompian la estructura del archivo.</p>
<p><strong>Proceso de limpieza realizado:</strong></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comandos utilizados para limpieza:</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Remover saltos de línea problemáticos</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="st">':a;N;$!ba;s/\n\([^0-9]\)/\1/g'</span> beacon_v6.tab <span class="op">&gt;</span> beacon_v6_temp.tab</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Conversión de TAB a CSV</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sed</span> <span class="st">'s/\t/,/g'</span> beacon_v6_temp.tab <span class="op">&gt;</span> beacon_v6_clean.csv</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Limpieza de archivos temporales</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span> beacon_v6_temp.tab</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultado: beacon_v6_clean.csv (87,170 registros limpios)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Validación post-limpieza:</strong></p>
<ul>
<li><strong>Registros preservados:</strong> 100% (87,170/87,170)</li>
<li><strong>Estructura validada:</strong> 31 columnas consistentes</li>
<li><strong>Formato:</strong> CSV estándar con separadores de coma</li>
<li><strong>Problema resuelto:</strong> Saltos de línea incrustados eliminados</li>
</ul>
<p><strong>1. Procesamiento Base</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Separar beacon v6 por tipo de aplicación</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts_v6/1_split_beacon_v6.py</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Input: beacon_v6_clean.csv (datos limpiados manualmente)</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: beacon_v6_ojs.csv (86,282 instalaciones)</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Análisis global v6</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts_v6/2_analisis_mundial_v6.R</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations_v6/top15_paises_barras_v6.png</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>2. Análisis Chile v6</strong></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar instalaciones chilenas con criterios v6</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts_v6/3_analisis_chile_v6.R</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations_v6/chile_todas_instalaciones_v6.csv (432)</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Aplicar criterio JUOJS actualizado (&gt;5 pub/2024)</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts_v6/4_chile_juojs_filtrado_v6.R</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations_v6/chile_juojs_activas_v6.csv (319 - DATASET PRINCIPAL)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>3. Evaluación Dialnet v6</strong></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar URLs OAI desde dataset JUOJS v6</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts_v6/5_generar_urls_dialnet_v6.py</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: visualizations_v6/chile_oai_urls_v6.csv (225 URLs únicas)</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>4. Análisis y Visualizaciones</strong></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generar tablas y análisis institucional</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="ex">Rscript</span> scripts_v6/6_tablas_chile_v6.R</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Genera: tablas CSV y análisis institucional</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="decisión-metodológica-continuidad-operativa-v5" class="level4">
<h4 class="anchored" data-anchor-id="decisión-metodológica-continuidad-operativa-v5">2.2.3 Decisión metodológica: continuidad operativa v5</h4>
<p>Luego de una validación cruzada entre ambas versiones mediante el script <code>7_comparar_urls_v5_v6.py</code>, se decide continuar operativamente con las fuentes producto de la v5:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparación precisa entre versiones por dominio</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> scripts/7_comparar_urls_v5_v6.py</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Compara: chile_oai_urls_limpio.csv (208 URLs) vs chile_oai_urls_limpio_v6.csv (225 URLs)</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultados: 88.9% estabilidad, +17 URLs netas, 0 cambios sustanciales</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Resultados de la validación cruzada:</strong></p>
<ul>
<li><strong>Estabilidad confirmada:</strong> 88.9% de dominios efectivamente iguales</li>
<li><strong>Dominios nuevos en v6:</strong> 40 (principalmente nuevas revistas)</li>
<li><strong>Dominios removidos:</strong> 23 (revistas inactivas o filtradas)</li>
<li><strong>Cambios menores:</strong> 7 (solo variaciones de www, protocolo o path)</li>
<li><strong>Cambios sustanciales:</strong> 0 (sin modificaciones de dominio)</li>
<li><strong>Crecimiento neto real:</strong> +17 dominios</li>
</ul>
<p>Dada la alta estabilidad entre versiones y que los datos v5 ya están procesados con <strong>95 informes Dialnet descargados</strong>, se continúa el procesamiento sobre resultados v5 para análisis de calidad y evaluación. Paralelamente, se avanza con la descarga de informes Dialnet para las 40 URLs nuevas de v6.</p>
<p><strong>Implicaciones operativas:</strong></p>
<ul>
<li><strong>Dataset principal:</strong> chile_juojs_activas.csv (v5) - 316 instalaciones</li>
<li><strong>URLs evaluables v5:</strong> 208 URLs únicas (95 informes Dialnet procesados)</li>
<li><strong>Dataset validación:</strong> chile_juojs_activas_v6.csv - 319 instalaciones<br>
</li>
<li><strong>URLs evaluables v6:</strong> 225 URLs únicas (40 nuevas para procesamiento)</li>
</ul>
<p><strong>Cambios confirmados en el dataset:</strong></p>
<ul>
<li><strong>Instalaciones totales Chile:</strong> 403 → 432 (+29, +7.2%)</li>
<li><strong>Instalaciones activas:</strong> 316 → 319 (+3, +0.9%)</li>
<li><strong>Criterio temporal:</strong> 2023 → 2024 (actualización metodológica)</li>
<li><strong>URLs únicas:</strong> 208 → 225 (+17, +8.2%)</li>
</ul>
</section>
<section id="metodología-de-enriquecimiento-openalex" class="level4">
<h4 class="anchored" data-anchor-id="metodología-de-enriquecimiento-openalex">2.2.4 Metodología de enriquecimiento OpenAlex</h4>
<p>Para complementar los datos del PKP Beacon con indicadores de impacto académico internacional, se desarrolló un proceso de integración con la base de datos OpenAlex. Esta metodología permitió enriquecer el dataset original con métricas de visibilidad que proporcionan una perspectiva más amplia del alcance e influencia de las revistas OJS a nivel global.</p>
<p>El proceso de enriquecimiento se implementó mediante la consulta sistemática de la API de OpenAlex, obteniendo cuatro métricas fundamentales para cada revista: el número de trabajos indexados (works_count), el total de citaciones recibidas (cited_by_count), el índice H de la revista (h_index), y el promedio de citaciones en los últimos dos años (2yr_mean_citedness). Estas métricas proporcionan una base sólida para evaluar tanto la productividad como el impacto de las publicaciones.</p>
<p>A partir de estos datos primarios, se calcularon tres índices derivados que permiten una segmentación más precisa del ecosistema de revistas. El índice de visibilidad relaciona las citaciones totales con el número de artículos reportados en el Beacon, mientras que el índice de visibilidad ajustado considera únicamente los artículos efectivamente indexados en OpenAlex. Adicionalmente, la tasa de indexación mide qué proporción de la producción total de cada revista ha logrado visibilidad en bases de datos internacionales.</p>
<p>Esta metodología permitió establecer criterios de segmentación estratégica que identifican diferentes perfiles de revistas. Las revistas estrella se caracterizan por combinar un índice de visibilidad superior a 5.0 con un índice H de al menos 25 puntos. Las oportunidades de mejora corresponden a publicaciones con alta productividad (más de 500 artículos totales) pero baja visibilidad (inferior a 2.0). Las revistas emergentes presentan un índice H entre 5 y 24 puntos, con evidencia de crecimiento sostenido e indexación reciente. Finalmente, la priorización institucional considera la combinación de citaciones totales, número de revistas y visibilidad promedio por institución.</p>
</section>
</section>
</section>
<section id="resultados" class="level2">
<h2 class="anchored" data-anchor-id="resultados">3. Resultados</h2>
<section id="análisis-global" class="level3">
<h3 class="anchored" data-anchor-id="análisis-global">3.1 Análisis global</h3>
<section id="ecosistema-global-v5-línea-base" class="level4">
<h4 class="anchored" data-anchor-id="ecosistema-global-v5-línea-base">3.1.1 Ecosistema global v5 (línea base)</h4>
<p>Los datos del PKP Beacon v5 confirman la consolidación del ecosistema OJS como plataforma dominante en la publicación académica de acceso abierto, con <strong>49,790 instalaciones activas</strong> que representan el <strong>74.8%</strong> del total de instalaciones OJS identificadas. Esta tasa de actividad refleja un ecosistema maduro donde tres de cada cuatro instalaciones mantienen productividad editorial sostenida según el criterio DOAJ de más de 5 publicaciones anuales.</p>
<p>La <strong>diversidad geográfica</strong> es notable, con <strong>153 países</strong> representados, evidenciando la adopción global de OJS como herramienta de democratización del conocimiento científico. El volumen de <strong>2,018,793 publicaciones en 2023</strong> posiciona al ecosistema OJS como un actor significativo en la producción académica mundial, contribuyendo sustancialmente al acceso abierto global.</p>
<p>El <strong>acervo histórico de 10.6 millones de artículos</strong> demuestra la madurez del ecosistema y su papel como repositorio de conocimiento científico acumulado, estableciendo una base sólida para el crecimiento futuro y la preservación digital del patrimonio académico global.</p>
<p><strong>Distribución General v5:</strong></p>
<ul>
<li><strong>Total instalaciones procesadas:</strong> 67,138</li>
<li><strong>Instalaciones OJS:</strong> 66,527 (99.1%)</li>
<li><strong>Instalaciones OMP:</strong> 562 (0.8%)</li>
<li><strong>Instalaciones OPS:</strong> 49 (0.1%)</li>
</ul>
<p><strong>Instalaciones OJS Activas Globalmente v5:</strong></p>
<ul>
<li><strong>Total instalaciones OJS activas:</strong> 49,790 (74.8% del total OJS)</li>
<li><strong>Publicaciones 2023:</strong> 2,018,793 (línea base)</li>
<li><strong>Acervo histórico:</strong> 10.6 millones de artículos</li>
<li><strong>Países representados:</strong> 153 países activos</li>
</ul>
<table class="caption-top table">
<caption>Top 10 Países por Instalaciones Activas 2023 (v5)</caption>
<thead>
<tr class="header">
<th>País</th>
<th>Instalaciones Activas</th>
<th>Pub. 2023</th>
<th>Promedio por Instalación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Indonesia (ID)</td>
<td>22,208</td>
<td>652,762</td>
<td>29.4</td>
</tr>
<tr class="even">
<td>Brasil (BR)</td>
<td>3,944</td>
<td>198,007</td>
<td>50.2</td>
</tr>
<tr class="odd">
<td>Desconocido</td>
<td>1,617</td>
<td>97,779</td>
<td>60.5</td>
</tr>
<tr class="even">
<td>Estados Unidos (US)</td>
<td>1,545</td>
<td>71,604</td>
<td>46.3</td>
</tr>
<tr class="odd">
<td>India (IN)</td>
<td>1,362</td>
<td>83,428</td>
<td>61.3</td>
</tr>
<tr class="even">
<td>España (ES)</td>
<td>1,260</td>
<td>45,441</td>
<td>36.1</td>
</tr>
<tr class="odd">
<td>Tailandia (TH)</td>
<td>1,088</td>
<td>40,254</td>
<td>37.0</td>
</tr>
<tr class="even">
<td>Ucrania (UA)</td>
<td>1,002</td>
<td>63,444</td>
<td>63.3</td>
</tr>
<tr class="odd">
<td>Rusia (RU)</td>
<td>907</td>
<td>74,527</td>
<td>82.2</td>
</tr>
<tr class="even">
<td>Pakistán (PK)</td>
<td>843</td>
<td>33,571</td>
<td>39.8</td>
</tr>
</tbody>
</table>
<p>Indonesia domina con el 44.6% de las instalaciones activas globales, seguido por Brasil (7.9%) y Estados Unidos (3.1%). Chile ocupa la posición 25 con 311 instalaciones activas, representando el 0.6% del ecosistema global.</p>
</section>
<section id="ecosistema-global-v6-validación-actualizada" class="level4">
<h4 class="anchored" data-anchor-id="ecosistema-global-v6-validación-actualizada">3.1.2 Ecosistema global v6 (validación actualizada)</h4>
<p>Los datos del PKP Beacon v6 confirman la continuidad del crecimiento del ecosistema OJS, alcanzando <strong>54,453 instalaciones activas</strong> que representan el <strong>63.1%</strong> del total de instalaciones OJS identificadas. Aunque la tasa de actividad muestra una ligera disminución porcentual respecto a v5, el aumento absoluto de instalaciones activas (+4,663) indica una expansión sostenida del ecosistema.</p>
<p><strong>Distribución General v6:</strong></p>
<ul>
<li><strong>Total instalaciones procesadas:</strong> 87,170 (+29.8% vs v5)</li>
<li><strong>Instalaciones OJS:</strong> 86,282 (99.0%)</li>
<li><strong>Instalaciones OMP:</strong> 810 (0.9%)</li>
<li><strong>Instalaciones OPS:</strong> 78 (0.1%)</li>
<li><strong>Países representados:</strong> 154 países activos (+1 vs v5)</li>
</ul>
<p><strong>Instalaciones OJS Activas Globalmente v6:</strong></p>
<ul>
<li><strong>Total instalaciones OJS activas:</strong> 54,453 (63.1% del total, +4,663 vs v5)</li>
<li><strong>Publicaciones 2024:</strong> 2,365,938 (+28.4% vs 2023)</li>
<li><strong>Crecimiento 2023→2024:</strong> +516,768 publicaciones</li>
<li><strong>Cambio en actividad:</strong> Consolidación del crecimiento global</li>
</ul>
<table class="caption-top table">
<caption>Validación v6: Top 10 Países por Instalaciones Activas 2024</caption>
<thead>
<tr class="header">
<th>País</th>
<th>Instalaciones Activas</th>
<th>Pub. 2024</th>
<th>Crecimiento 2023→2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Indonesia (ID)</td>
<td>23,045</td>
<td>713,408</td>
<td>+122,211</td>
</tr>
<tr class="even">
<td>Brasil (BR)</td>
<td>4,050</td>
<td>228,789</td>
<td>+48,856</td>
</tr>
<tr class="odd">
<td>Desconocido</td>
<td>3,260</td>
<td>161,446</td>
<td>+87,204</td>
</tr>
<tr class="even">
<td>Estados Unidos (US)</td>
<td>1,714</td>
<td>87,977</td>
<td>+26,968</td>
</tr>
<tr class="odd">
<td>India (IN)</td>
<td>1,630</td>
<td>95,726</td>
<td>+22,334</td>
</tr>
<tr class="even">
<td>España (ES)</td>
<td>1,295</td>
<td>57,190</td>
<td>+13,336</td>
</tr>
<tr class="odd">
<td>Tailandia (TH)</td>
<td>1,172</td>
<td>43,923</td>
<td>+5,298</td>
</tr>
<tr class="even">
<td>Ucrania (UA)</td>
<td>1,052</td>
<td>73,371</td>
<td>+13,299</td>
</tr>
<tr class="odd">
<td>Rusia (RU)</td>
<td>954</td>
<td>74,346</td>
<td>+6,280</td>
</tr>
<tr class="even">
<td>Pakistán (PK)</td>
<td>893</td>
<td>43,070</td>
<td>+11,921</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<caption>Validación v6: Distribución por Regiones PKP</caption>
<thead>
<tr class="header">
<th>Región PKP</th>
<th>Instalaciones</th>
<th>Pub. 2024</th>
<th>Países</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>East Asia &amp; Pacific</td>
<td>25,767</td>
<td>873,834</td>
<td>22</td>
</tr>
<tr class="even">
<td>Europe &amp; Central Asia</td>
<td>9,112</td>
<td>543,986</td>
<td>47</td>
</tr>
<tr class="odd">
<td>Latin America &amp; Caribbean</td>
<td>8,485</td>
<td>377,023</td>
<td>22</td>
</tr>
<tr class="even">
<td>Other</td>
<td>3,325</td>
<td>164,692</td>
<td>22</td>
</tr>
<tr class="odd">
<td>South Asia</td>
<td>3,099</td>
<td>151,324</td>
<td>8</td>
</tr>
<tr class="even">
<td>North America</td>
<td>2,110</td>
<td>103,790</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Sub-Saharan Africa</td>
<td>1,525</td>
<td>57,713</td>
<td>33</td>
</tr>
<tr class="even">
<td>Middle East &amp; North Africa</td>
<td>1,030</td>
<td>64,297</td>
<td>19</td>
</tr>
</tbody>
</table>
</section>
<section id="comparación-global-v5-vs-v6" class="level4">
<h4 class="anchored" data-anchor-id="comparación-global-v5-vs-v6">3.1.3 Comparación global v5 vs v6</h4>
<p><strong>Crecimiento del Ecosistema:</strong></p>
<ul>
<li><strong>Instalaciones totales:</strong> 67,138 → 87,170 (+29.8%)</li>
<li><strong>Instalaciones OJS:</strong> 66,527 → 86,282 (+29.7%)</li>
<li><strong>Instalaciones activas:</strong> 49,790 → 54,453 (+9.4%)</li>
<li><strong>Publicaciones anuales:</strong> 2,018,793 → 2,365,938 (+17.2%)</li>
<li><strong>Países activos:</strong> 153 → 154 (+0.7%)</li>
</ul>
</section>
</section>
<section id="análisis-específico-de-chile" class="level3">
<h3 class="anchored" data-anchor-id="análisis-específico-de-chile">3.2 Análisis específico de Chile</h3>
<p>El ecosistema editorial chileno representa un caso paradigmático de adopción y consolidación de Open Journal Systems en América Latina. Con <strong>432 instalaciones identificadas</strong> en la validación v6 y un crecimiento sostenido del <strong>16.5%</strong> en publicaciones entre 2023 y 2024, Chile ocupa la <strong>posición 25 a nivel global</strong> con 319 instalaciones activas, posicionándose como el <strong>séptimo país</strong> más activo de América Latina en el uso de OJS, después de Brasil (4,050), Colombia (795), Argentina (780), México (774), Ecuador (408) y Perú (400).</p>
<p>La <strong>diversidad institucional</strong> del ecosistema chileno es notable, con la Universidad de Chile liderando en número de instalaciones (20.6%) y la Pontificia Universidad Católica destacando por su alta productividad promedio. Esta distribución refleja tanto la madurez del sistema universitario chileno como la adopción estratégica del acceso abierto en diferentes contextos institucionales.</p>
<p>El análisis longitudinal entre las versiones v5 y v6 del PKP Beacon revela un ecosistema en <strong>expansión controlada</strong>, donde el 51.1% de las instalaciones experimentaron crecimiento positivo, evidenciando una dinámica editorial saludable que combina estabilidad institucional con innovación en la publicación académica.</p>
<table class="caption-top table">
<caption>Top 10 Países de América Latina por Instalaciones OJS Activas 2024 (v6)</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 29%">
<col style="width: 14%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Posición</th>
<th>País</th>
<th>Instalaciones Activas</th>
<th>Pub. 2024</th>
<th>Promedio por Instalación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Brasil (BR)</td>
<td>4,050</td>
<td>228,789</td>
<td>56.5</td>
</tr>
<tr class="even">
<td>2</td>
<td>Colombia (CO)</td>
<td>795</td>
<td>20,150</td>
<td>25.3</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Argentina (AR)</td>
<td>780</td>
<td>24,395</td>
<td>31.3</td>
</tr>
<tr class="even">
<td>4</td>
<td>México (MX)</td>
<td>774</td>
<td>26,821</td>
<td>34.7</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Ecuador (EC)</td>
<td>408</td>
<td>15,151</td>
<td>37.1</td>
</tr>
<tr class="even">
<td>6</td>
<td>Perú (PE)</td>
<td>400</td>
<td>11,010</td>
<td>27.5</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Chile (CL)</td>
<td>319</td>
<td>14,162</td>
<td>44.4</td>
</tr>
<tr class="even">
<td>8</td>
<td>Venezuela (VE)</td>
<td>234</td>
<td>9,149</td>
<td>39.1</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Paraguay (PY)</td>
<td>104</td>
<td>7,093</td>
<td>68.2</td>
</tr>
<tr class="even">
<td>10</td>
<td>Bolivia (BO)</td>
<td>92</td>
<td>2,041</td>
<td>22.2</td>
</tr>
</tbody>
</table>
<p>Brasil domina claramente el ecosistema latinoamericano con 4,050 instalaciones (47.7% del total regional), seguido por Colombia, Argentina y México con volúmenes similares entre 774-795 instalaciones. Chile, con 319 instalaciones activas, representa el 3.8% del ecosistema latinoamericano y muestra una productividad promedio competitiva de 44.4 publicaciones por instalación.</p>
<section id="ecosistema-chileno-v5-dataset-principal" class="level4">
<h4 class="anchored" data-anchor-id="ecosistema-chileno-v5-dataset-principal">3.2.1 Ecosistema chileno v5 (dataset principal)</h4>
<p>El análisis del ecosistema chileno v5 establece la <strong>línea base metodológica</strong> para la caracterización integral del sector editorial académico nacional. Con <strong>316 instalaciones activas</strong> identificadas mediante el criterio DOAJ de más de 5 publicaciones anuales, Chile demuestra una <strong>alta tasa de actividad editorial</strong> del 78.4%, superando significativamente el promedio global del 74.8%.</p>
<p>La <strong>concentración de productividad</strong> revela patrones característicos del ecosistema chileno: mientras que las 10 revistas más productivas concentran el 45.2% de las publicaciones totales, existe una <strong>distribución equilibrada</strong> en el segmento medio, con 177 instalaciones clasificadas como “otras instituciones” que representan el 56% del total, evidenciando una diversificación saludable del sector editorial.</p>
<p>El <strong>acervo histórico de 133,931 publicaciones</strong> posiciona a Chile como un contribuyente significativo al patrimonio académico latinoamericano, con un promedio de 423.8 artículos por instalación activa a lo largo de su historia editorial. Esta base sólida proporciona el contexto necesario para evaluar el crecimiento y la evolución del ecosistema hacia 2024.</p>
<p><strong>Estadísticas Generales v5:</strong></p>
<ul>
<li><strong>Total instalaciones identificadas:</strong> 403</li>
<li><strong>Instalaciones JUOJS activas (&gt;5 pub/2023):</strong> 316 (78.4%)</li>
<li><strong>Instalaciones filtradas:</strong> 87 (≤5 pub/2023)</li>
<li><strong>URLs únicas generadas para Dialnet:</strong> 208 (eliminados 107 duplicados)</li>
</ul>
<p><strong>Productividad 2023 (Línea Base v5):</strong></p>
<ul>
<li><strong>Total publicaciones 2023:</strong> 12,156</li>
<li><strong>Promedio por instalación activa:</strong> 38.5 pub/instalación</li>
<li><strong>Total histórico acumulado:</strong> 133,931 publicaciones</li>
</ul>
<table class="caption-top table">
<caption>Top 10 Instalaciones Más Productivas 2023 (v5)</caption>
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th>Revista/Contexto</th>
<th>Dominio</th>
<th>Pub. 2023</th>
<th>Total Histórico</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Revista Inclusiones</td>
<td>inclusiones.cl</td>
<td>2,671</td>
<td>2,671</td>
</tr>
<tr class="even">
<td>Onomázein</td>
<td>onomazein.net</td>
<td>1,081</td>
<td>1,081</td>
</tr>
<tr class="odd">
<td>Anales de Literatura Chilena</td>
<td>anales.uchile.cl</td>
<td>956</td>
<td>956</td>
</tr>
<tr class="even">
<td>REVISTA CUHSO</td>
<td>cuhso.uct.cl</td>
<td>910</td>
<td>910</td>
</tr>
<tr class="odd">
<td>Revista AIDIS</td>
<td>aidis.cl</td>
<td>897</td>
<td>897</td>
</tr>
<tr class="even">
<td>Boletín de la Universidad de Chile</td>
<td>revistasdex.uchile.cl</td>
<td>160</td>
<td>1,689</td>
</tr>
<tr class="odd">
<td>Revista de la construcción</td>
<td>revistadelaconstruccion.uc.cl</td>
<td>2,681</td>
<td>2,681</td>
</tr>
<tr class="even">
<td>Apuntes de Teatro</td>
<td>revistaapuntes.uc.cl</td>
<td>1,018</td>
<td>1,018</td>
</tr>
<tr class="odd">
<td>Revista Chilena de Derecho</td>
<td>revistachilenadederecho.uc.cl</td>
<td>37</td>
<td>1,708</td>
</tr>
<tr class="even">
<td>Ingeniare. Revista Chilena de Ingeniería</td>
<td>revistalimite.uta.cl</td>
<td>-</td>
<td>321</td>
</tr>
</tbody>
</table>
<p>La productividad se concentra en revistas de alta frecuencia editorial, con Revista Inclusiones liderando con 2,671 publicaciones en 2023. El ecosistema muestra diversidad disciplinaria desde ciencias sociales hasta ingeniería.</p>
<table class="caption-top table">
<caption>Distribución Institucional (v5)</caption>
<thead>
<tr class="header">
<th>Institución</th>
<th>Instalaciones</th>
<th>%</th>
<th>Pub. 2023</th>
<th>Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Universidad de Chile</td>
<td>65</td>
<td>20.6%</td>
<td>1,692</td>
<td>26.0</td>
</tr>
<tr class="even">
<td>Pontificia Universidad Católica</td>
<td>28</td>
<td>8.9%</td>
<td>4,567</td>
<td>163.1</td>
</tr>
<tr class="odd">
<td>Universidad de Valparaíso</td>
<td>16</td>
<td>5.1%</td>
<td>250</td>
<td>15.6</td>
</tr>
<tr class="even">
<td>Universidad de Concepción</td>
<td>13</td>
<td>4.1%</td>
<td>389</td>
<td>29.9</td>
</tr>
<tr class="odd">
<td>Universidad Austral de Chile</td>
<td>8</td>
<td>2.5%</td>
<td>272</td>
<td>34.0</td>
</tr>
<tr class="even">
<td>Universidad de Santiago</td>
<td>5</td>
<td>1.6%</td>
<td>122</td>
<td>24.4</td>
</tr>
<tr class="odd">
<td>Universidad de La Frontera</td>
<td>4</td>
<td>1.3%</td>
<td>45</td>
<td>11.3</td>
</tr>
<tr class="even">
<td>Otras instituciones</td>
<td>177</td>
<td>56.0%</td>
<td>4,819</td>
<td>27.2</td>
</tr>
</tbody>
</table>
<p>La Universidad de Chile lidera en número de instalaciones (20.6%) mientras que la UC muestra mayor productividad promedio por instalación (163.1 pub/instalación vs 26.0 de UChile).</p>
</section>
<section id="ecosistema-chileno-v6-validación-actualizada" class="level4">
<h4 class="anchored" data-anchor-id="ecosistema-chileno-v6-validación-actualizada">3.2.2 Ecosistema chileno v6 (validación actualizada)</h4>
<p><strong>Estadísticas Generales v6:</strong></p>
<ul>
<li><strong>Total instalaciones identificadas:</strong> 432 (+29 vs v5, +7.2%)</li>
<li><strong>Instalaciones JUOJS activas (&gt;5 pub/2024):</strong> 319 (+3 vs v5, +0.9%)</li>
<li><strong>Instalaciones filtradas:</strong> 113 (≤5 pub/2024)</li>
<li><strong>URLs únicas generadas:</strong> 225 (+17 vs v5, +8.2%)</li>
</ul>
<p><strong>Productividad 2024 (Validación v6):</strong></p>
<ul>
<li><strong>Total publicaciones 2024:</strong> 14,162</li>
<li><strong>Total publicaciones 2023:</strong> 12,156</li>
<li><strong>Crecimiento neto:</strong> +2,006 publicaciones (+16.5%)</li>
<li><strong>Promedio por instalación activa:</strong> 44.4 pub/instalación</li>
<li><strong>Total histórico acumulado:</strong> 144,529 publicaciones</li>
</ul>
<table class="caption-top table">
<caption>Validación v6: Top 10 Instalaciones Más Productivas 2024</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 15%">
<col style="width: 18%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Revista/Contexto</th>
<th>Dominio</th>
<th>Pub. 2024</th>
<th>Crecimiento vs 2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Revista Chilena de Derecho</td>
<td>revistachilenadederecho.uc.cl</td>
<td>1,708</td>
<td>+1,671</td>
</tr>
<tr class="even">
<td>Boletín de la Universidad de Chile</td>
<td>revistasdex.uchile.cl</td>
<td>1,689</td>
<td>+1,529</td>
</tr>
<tr class="odd">
<td>Boletín Jurídico del Observatorio</td>
<td>revistadelaconstruccion.uc.cl</td>
<td>958</td>
<td>-1,723</td>
</tr>
<tr class="even">
<td>REVISTA CUHSO</td>
<td>cuhso.uct.cl</td>
<td>510</td>
<td>+470</td>
</tr>
<tr class="odd">
<td>MGC / Revista de Gestión Cultural</td>
<td>revistasdex.uchile.cl</td>
<td>330</td>
<td>+218</td>
</tr>
<tr class="even">
<td>Ingeniare. Revista Chilena de Ingeniería</td>
<td>revistalimite.uta.cl</td>
<td>321</td>
<td>+321</td>
</tr>
<tr class="odd">
<td>Revista de Trabajo Social</td>
<td>revistadelaconstruccion.uc.cl</td>
<td>293</td>
<td>+277</td>
</tr>
<tr class="even">
<td>Revista de Historia Social y de las Mentalidades</td>
<td>www.revistas.usach.cl</td>
<td>221</td>
<td>+190</td>
</tr>
<tr class="odd">
<td>Apuntes de Teatro</td>
<td>revistaapuntes.uc.cl</td>
<td>214</td>
<td>-804</td>
</tr>
<tr class="even">
<td>Progress Annals: Journal of Progressive Research</td>
<td>academiaone.org</td>
<td>136</td>
<td>+83</td>
</tr>
</tbody>
</table>
</section>
<section id="validación-v6-análisis-de-crecimiento-2023-2024" class="level4">
<h4 class="anchored" data-anchor-id="validación-v6-análisis-de-crecimiento-2023-2024">3.2.7 Validación v6: análisis de crecimiento 2023-2024</h4>
<p>El análisis de crecimiento entre 2023 y 2024 revela un ecosistema editorial dinámico donde <strong>163 instalaciones experimentaron crecimiento positivo</strong>, representando el 51.1% del total. En contraste, <strong>135 instalaciones mostraron decrecimiento</strong> (42.3%), mientras que solo <strong>21 instalaciones se mantuvieron estables</strong> (6.6%). El <strong>crecimiento promedio de 6.3 publicaciones por instalación</strong> refleja una expansión moderada pero sostenida del ecosistema editorial chileno.</p>
<table class="caption-top table">
<caption>Validación v6: Distribución Institucional Actualizada</caption>
<thead>
<tr class="header">
<th>Institución</th>
<th>Instalaciones</th>
<th>%</th>
<th>Pub. 2024</th>
<th>Crecimiento</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Universidad de Chile</td>
<td>67</td>
<td>21.0%</td>
<td>3,338</td>
<td>+1,646</td>
</tr>
<tr class="even">
<td>Pontificia Universidad Católica</td>
<td>27</td>
<td>8.5%</td>
<td>4,129</td>
<td>-438</td>
</tr>
<tr class="odd">
<td>Universidad de Valparaíso</td>
<td>15</td>
<td>4.7%</td>
<td>227</td>
<td>-23</td>
</tr>
<tr class="even">
<td>Universidad de Concepción</td>
<td>12</td>
<td>3.8%</td>
<td>353</td>
<td>-36</td>
</tr>
<tr class="odd">
<td>Universidad Austral de Chile</td>
<td>7</td>
<td>2.2%</td>
<td>213</td>
<td>-59</td>
</tr>
<tr class="even">
<td>Universidad de Santiago</td>
<td>6</td>
<td>1.9%</td>
<td>299</td>
<td>+177</td>
</tr>
<tr class="odd">
<td>Universidad de La Frontera</td>
<td>4</td>
<td>1.3%</td>
<td>-</td>
<td>-</td>
</tr>
<tr class="even">
<td>Otras instituciones</td>
<td>181</td>
<td>56.7%</td>
<td>5,603</td>
<td>+739</td>
</tr>
</tbody>
</table>
</section>
<section id="comparación-chile-v5-vs-v6" class="level4">
<h4 class="anchored" data-anchor-id="comparación-chile-v5-vs-v6">3.2.3 Comparación Chile v5 vs v6</h4>
<p><strong>Crecimiento del ecosistema chileno:</strong></p>
<ul>
<li><strong>Instalaciones totales:</strong> 403 → 432 (+7.2%)</li>
<li><strong>Instalaciones activas:</strong> 316 → 319 (+0.9%)</li>
<li><strong>Publicaciones anuales:</strong> 12,156 → 14,162 (+16.5%)</li>
<li><strong>URLs evaluables:</strong> 208 → 225 (+8.2%)</li>
<li><strong>Acervo histórico:</strong> 133,931 → 144,529 (+7.9%)</li>
</ul>
</section>
</section>
<section id="análisis-de-calidad-editorial-informes-dialnet" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-calidad-editorial-informes-dialnet">3.3 Análisis de calidad editorial: informes Dialnet</h3>
<p>La evaluación de calidad editorial constituye un componente fundamental para la caracterización integral del ecosistema OJS chileno, complementando las métricas cuantitativas de productividad con indicadores cualitativos de excelencia académica. El sistema <strong>Dialnet Nexus</strong> de la Universidad de La Rioja proporciona una metodología estandarizada para evaluar la completitud de metadatos, coherencia editorial y adherencia a estándares internacionales de publicación académica.</p>
<p>El análisis procesado abarca <strong>95 revistas chilenas</strong> (45.7% de las 208 URLs únicas generadas), representando una <strong>muestra significativa</strong> que incluye tanto revistas de alta productividad como instalaciones de menor volumen, garantizando la representatividad del diagnóstico. La metodología de Dialnet identifica <strong>40 tipos de errores</strong> clasificados por gravedad, proporcionando un marco sistemático para priorizar intervenciones de mejora.</p>
<p>Los resultados revelan un <strong>panorama heterogéneo</strong> donde ninguna revista alcanza estándares perfectos, pero el 71.6% mantiene niveles de error manejables (&lt;1000 errores), evidenciando oportunidades concretas de mejora que pueden impactar significativamente la visibilidad internacional y la indexación en bases de datos especializadas.</p>
<section id="procesamiento-de-informes" class="level4">
<h4 class="anchored" data-anchor-id="procesamiento-de-informes">3.3.1 Procesamiento de informes</h4>
<p>Luego de procesar <strong>95 informes HTML</strong> de Dialnet descargados manualmente y extraer información estructurada sobre errores de calidad y completitud de metadatos mediante <code>scripts/8_procesar_informes_dialnet.py</code> se obtienen los siguientes resultados:</p>
<p><strong>Cobertura del análisis:</strong> - <strong>Total informes procesados:</strong> 95 revistas chilenas - <strong>Archivo generado:</strong> <code>visualizations/dialnet_informes_procesados.csv</code> - <strong>Datos extraídos:</strong> Errores por gravedad, tipos de errores, porcentajes de metadatos</p>
</section>
<section id="resultados-de-calidad-editorial" class="level4">
<h4 class="anchored" data-anchor-id="resultados-de-calidad-editorial">3.3.2 Resultados de calidad editorial</h4>
<p><strong>Estado general de errores:</strong> - <strong>Revistas sin errores:</strong> 0 (0.0%) - <strong>Revistas con errores:</strong> 95 (100.0%) - <strong>Total errores detectados:</strong> 59,602 - <strong>Alta gravedad:</strong> 35,811 (60.1%) - <strong>Media gravedad:</strong> 23,791 (39.9%) - <strong>Promedio errores por revista:</strong> 627.4</p>
</section>
<section id="revistas-con-mayor-número-de-errores" class="level4">
<h4 class="anchored" data-anchor-id="revistas-con-mayor-número-de-errores">3.3.3 Revistas con mayor número de errores</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ranking</th>
<th>Dominio</th>
<th>Total Errores</th>
<th>Alta Gravedad</th>
<th>Media Gravedad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>www.revistasdex.uchile.cl</td>
<td>5,583</td>
<td>2,626</td>
<td>2,957</td>
</tr>
<tr class="even">
<td>2</td>
<td>revistas.uach.cl</td>
<td>3,881</td>
<td>1,607</td>
<td>2,274</td>
</tr>
<tr class="odd">
<td>3</td>
<td>revistas.uv.cl</td>
<td>2,865</td>
<td>1,988</td>
<td>877</td>
</tr>
<tr class="even">
<td>4</td>
<td>rhv.uv.cl</td>
<td>2,865</td>
<td>1,988</td>
<td>877</td>
</tr>
<tr class="odd">
<td>5</td>
<td>www.iace.uv.cl</td>
<td>2,865</td>
<td>1,988</td>
<td>877</td>
</tr>
</tbody>
</table>
</section>
<section id="completitud-de-metadatos" class="level4">
<h4 class="anchored" data-anchor-id="completitud-de-metadatos">3.3.4 Completitud de metadatos</h4>
<p><strong>Promedios de completitud por tipo de metadato:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo de Metadato</th>
<th>Completitud Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Títulos</td>
<td>100.0%</td>
</tr>
<tr class="even">
<td>Enlaces</td>
<td>100.0%</td>
</tr>
<tr class="odd">
<td>Autores</td>
<td>99.3%</td>
</tr>
<tr class="even">
<td>Resúmenes</td>
<td>87.0%</td>
</tr>
<tr class="odd">
<td>Afiliaciones</td>
<td>75.6%</td>
</tr>
<tr class="even">
<td>Palabras clave</td>
<td>65.6%</td>
</tr>
<tr class="odd">
<td>Referencias</td>
<td>33.7%</td>
</tr>
</tbody>
</table>
</section>
<section id="análisis-de-tipos-de-errores-por-gravedad" class="level4">
<h4 class="anchored" data-anchor-id="análisis-de-tipos-de-errores-por-gravedad">3.3.5 Análisis de tipos de errores por gravedad</h4>
<p><strong>Top 5 errores de alta gravedad más frecuentes:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ranking</th>
<th>Tipo de Error</th>
<th>Ocurrencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Artículo sin número de página inicial</td>
<td>12,201</td>
</tr>
<tr class="even">
<td>2</td>
<td>Artículo sin ejemplar identificado en la importación</td>
<td>6,964</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Artículo con título y subtítulo en mayúsculas</td>
<td>6,810</td>
</tr>
<tr class="even">
<td>4</td>
<td>Artículo con resumen repetido para la misma revista</td>
<td>2,056</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Artículo con autorías duplicadas</td>
<td>1,968</td>
</tr>
</tbody>
</table>
<p><strong>Top 5 errores de media gravedad más frecuentes:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 40%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Ranking</th>
<th>Tipo de Error</th>
<th>Ocurrencias</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Autor con apellido 2 de longitud menor de 4 caracteres</td>
<td>6,468</td>
</tr>
<tr class="even">
<td>2</td>
<td>Ejemplar marcado como no paginado y contiene artículos con página final</td>
<td>5,257</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Artículo con título repetido para la misma revista</td>
<td>2,721</td>
</tr>
<tr class="even">
<td>4</td>
<td>Artículo con referencias cuyo literal es demasiado corto</td>
<td>2,080</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Artículo con título repetido</td>
<td>1,843</td>
</tr>
</tbody>
</table>
<p><strong>Distribución de revistas por rangos de errores:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rango de Errores</th>
<th>Nº Revistas</th>
<th>Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Muy Alto (&gt;2000)</td>
<td>9</td>
<td>9.5%</td>
</tr>
<tr class="even">
<td>Alto (1000-2000)</td>
<td>10</td>
<td>10.5%</td>
</tr>
<tr class="odd">
<td>Medio (500-999)</td>
<td>8</td>
<td>8.4%</td>
</tr>
<tr class="even">
<td>Bajo (100-499)</td>
<td>43</td>
<td>45.3%</td>
</tr>
<tr class="odd">
<td>Muy Bajo (&lt;100)</td>
<td>25</td>
<td>26.3%</td>
</tr>
</tbody>
</table>
<p><strong>Revistas con mayor proporción de errores graves:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ranking</th>
<th>Dominio</th>
<th>% Alta Gravedad</th>
<th>Errores Alta/Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>revistaderechovaldivia.cl</td>
<td>97.6%</td>
<td>1,160/1,188</td>
</tr>
<tr class="even">
<td>2</td>
<td>intushistoria.uai.cl</td>
<td>97.6%</td>
<td>775/794</td>
</tr>
<tr class="odd">
<td>3</td>
<td>boletin.scha.cl</td>
<td>94.6%</td>
<td>2,390/2,526</td>
</tr>
<tr class="even">
<td>4</td>
<td>nuestramerica.cl</td>
<td>92.9%</td>
<td>351/378</td>
</tr>
<tr class="odd">
<td>5</td>
<td>revistalimite.uta.cl</td>
<td>91.9%</td>
<td>846/921</td>
</tr>
</tbody>
</table>
<p><strong>Diversidad de tipos de errores:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Categoría</th>
<th>Tipos Únicos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Alta gravedad</td>
<td>23</td>
</tr>
<tr class="even">
<td>Media gravedad</td>
<td>17</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>40</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="implicaciones-para-indexación" class="level4">
<h4 class="anchored" data-anchor-id="implicaciones-para-indexación">3.3.6 Implicaciones para indexación</h4>
<p>Los hallazgos del análisis Dialnet proporcionan un <strong>diagnóstico estratégico</strong> para la indexación internacional de revistas chilenas, revelando tanto fortalezas consolidadas como áreas críticas que requieren intervención prioritaria. La <strong>heterogeneidad en la calidad editorial</strong> observada (desde 25 revistas con &lt;100 errores hasta 9 con &gt;2000 errores) sugiere la necesidad de estrategias diferenciadas que maximicen el impacto de las intervenciones.</p>
<p>La <strong>alta completitud en metadatos básicos</strong> (títulos 100%, autores 99.3%) establece una base sólida para la indexación, mientras que las <strong>deficiencias críticas en referencias bibliográficas</strong> (33.7%) y <strong>palabras clave</strong> (65.6%) representan barreras significativas para el reconocimiento en bases de datos especializadas como Scopus, Web of Science y DOAJ.</p>
<p>El <strong>patrón de errores identificado</strong> revela problemas sistemáticos en la gestión editorial: 12,201 artículos sin paginación adecuada y 6,810 casos de formato incorrecto en títulos indican la necesidad de <strong>capacitación editorial especializada</strong> y <strong>implementación de protocolos de calidad</strong> que pueden resolverse mediante intervenciones focalizadas.</p>
<p><strong>Fortalezas identificadas</strong></p>
<p>El ecosistema editorial chileno demuestra <strong>solidez en metadatos fundamentales</strong> con títulos y enlaces al 100% de completitud, estableciendo una base técnica robusta para la indexación. La <strong>información de autoría</strong> alcanza un 99.3% de completitud, cumpliendo estándares internacionales de identificación académica. El <strong>contenido académico</strong> muestra fortaleza con 87% de resúmenes disponibles, proporcionando la información descriptiva esencial para la discovrabilidad en bases de datos especializadas.</p>
<p><strong>Áreas de mejora críticas</strong></p>
<p>Las <strong>referencias bibliográficas</strong> representan la deficiencia más crítica con solo 33.7% de completitud, limitando significativamente las posibilidades de indexación en Scopus y Web of Science. Las <strong>palabras clave</strong> requieren mejora urgente (65.6% completitud) para optimizar la discovrabilidad temática. Los <strong>35,811 errores de alta gravedad</strong> demandan atención prioritaria, especialmente los <strong>12,201 artículos sin página inicial</strong> que comprometen la citabilidad. La <strong>estandarización de títulos</strong> necesita corrección en 6,810 casos con formato incorrecto de mayúsculas.</p>
<p><strong>Recomendaciones operativas</strong></p>
<p>La estrategia de mejora debe <strong>priorizar por calidad</strong>, enfocando recursos en las 25 revistas con menos de 100 errores para maximizar el retorno de inversión. La <strong>mejora de metadatos</strong> requiere implementación de estándares específicos para referencias bibliográficas y palabras clave mediante protocolos editoriales actualizados. Los <strong>programas de capacitación editorial</strong> deben abordar sistemáticamente los errores más frecuentes identificados. La <strong>corrección de paginación</strong> debe atender prioritariamente los 12,201 artículos sin numeración adecuada. La <strong>estandarización de formato</strong> debe corregir las mayúsculas incorrectas en títulos y subtítulos mediante revisión editorial sistemática.</p>
</section>
</section>
<section id="análisis-de-visibilidad-académica-integración-openalex" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-visibilidad-académica-integración-openalex">3.4 Análisis de visibilidad académica: integración OpenAlex</h3>
<p>La evaluación de <strong>visibilidad académica internacional</strong> constituye el complemento estratégico al análisis de calidad editorial, proporcionando métricas cuantitativas de impacto y reconocimiento científico que trascienden las fronteras nacionales. <strong>OpenAlex</strong>, como base de datos académica de acceso abierto con más de 200 millones de trabajos indexados, ofrece una perspectiva integral del posicionamiento de las revistas chilenas en el ecosistema científico global.</p>
<p><strong>El análisis se desarrolló en tres fases metodológicas progresivas</strong>: un análisis preliminar (Script 11) que estableció las métricas base filtrando datos del beacon global, seguido de un análisis estratégico de segmentación (Script 12), y culminando con un <strong>análisis ampliado y definitivo (Script 13)</strong> que incorporó consulta directa a OpenAlex para las 316 revistas chilenas activas, logrando una cobertura superior (85.2% vs 46.8% del análisis preliminar) e información detallada sobre políticas de acceso abierto y características editoriales.</p>
<p>La integración de métricas OpenAlex con el dataset PKP Beacon permite identificar <strong>brechas de visibilidad</strong> donde revistas de alta productividad editorial mantienen bajo reconocimiento internacional, así como <strong>casos de éxito</strong> que demuestran el potencial del ecosistema chileno para alcanzar estándares internacionales de excelencia. Los <strong>resultados definitivos (Script 13)</strong> revelan que el 85.2% de las revistas chilenas logra indexación en OpenAlex, con el 94.6% siendo completamente de acceso abierto.</p>
<p>El análisis estratégico resultante confirma el <strong>liderazgo absoluto de JOTMI</strong> (Journal of Technology Management &amp; Innovation) con H-index 51, seguido por Estudios Pedagógicos y Journal of the Chilean Chemical Society (ambos con H-index 44). Se identifica una <strong>concentración del impacto en ciencias aplicadas, educación y químicas</strong>, con oportunidades de mejora para indexación en DOAJ. La <strong>priorización institucional</strong> confirma el liderazgo de instituciones clave en el ecosistema editorial académico chileno.</p>
<section id="resultados-de-visibilidad-global" class="level4">
<h4 class="anchored" data-anchor-id="resultados-de-visibilidad-global">3.4.1 Resultados de visibilidad global</h4>
<p>El proceso de enriquecimiento abarcó un total de 55,643 revistas que contaban con ISSN válido, logrando una cobertura exitosa en la consulta a OpenAlex. Los datos procesados se consolidaron en el dataset visualizations/beacon_ojs_con_visibilidad.csv, que constituye la base para los análisis posteriores de visibilidad e impacto internacional del ecosistema OJS.</p>
<p>Esta integración representa un avance significativo en la comprensión del alcance global de las revistas de acceso abierto, proporcionando por primera vez una visión integral que combina datos de productividad editorial con métricas de impacto académico internacional.</p>
</section>
<section id="análisis-preliminar-chile-script-11" class="level4">
<h4 class="anchored" data-anchor-id="análisis-preliminar-chile-script-11">3.4.2 Análisis preliminar Chile (Script 11)</h4>
<p><strong>Nota metodológica:</strong> Este análisis preliminar utilizó datos filtrados del beacon global enriquecido, proporcionando una primera aproximación a las métricas de visibilidad. Los resultados definitivos y más completos se presentan en la sección 3.4.5 (Script 13) mediante consulta directa a OpenAlex.</p>
<p><strong>Limitaciones del análisis preliminar:</strong> - <strong>Cobertura limitada</strong>: 148 de 316 revistas (46.8%) - <strong>Metodología indirecta</strong>: Filtrado de datos globales vs consulta específica - <strong>Campos restringidos</strong>: Métricas básicas sin información de políticas OA</p>
<p><strong>Justificación del análisis ampliado:</strong> La baja cobertura del 46.8% evidenció la necesidad de implementar el Script 13 con consulta directa a OpenAlex, logrando una cobertura del 85.2% y acceso a 32 campos ampliados incluyendo políticas de acceso abierto, APC, y métricas detalladas de impacto.</p>
</section>
<section id="análisis-estratégico-de-visibilidad-script-12" class="level4">
<h4 class="anchored" data-anchor-id="análisis-estratégico-de-visibilidad-script-12">3.4.3 Análisis estratégico de visibilidad (Script 12)</h4>
<p><strong>Categorización por rangos de visibilidad:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rango de Visibilidad</th>
<th>Nº Revistas</th>
<th>Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Baja (0.01-0.99)</td>
<td>52</td>
<td>47.7%</td>
</tr>
<tr class="even">
<td>Media (1-4.99)</td>
<td>30</td>
<td>27.5%</td>
</tr>
<tr class="odd">
<td>Sin citaciones (0)</td>
<td>22</td>
<td>20.2%</td>
</tr>
<tr class="even">
<td>Muy Alta (≥10)</td>
<td>3</td>
<td>2.8%</td>
</tr>
<tr class="odd">
<td>Alta (5-9.99)</td>
<td>2</td>
<td>1.8%</td>
</tr>
</tbody>
</table>
<p><strong>Top 10 revistas chilenas por H-index (Script 13 - Datos definitivos OpenAlex):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Revista</th>
<th>H-index</th>
<th>Citaciones</th>
<th>Trabajos</th>
<th>Acceso Abierto</th>
<th>DOAJ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Journal of Technology Management &amp; Innovation</td>
<td>51</td>
<td>13,607</td>
<td>892</td>
<td>Sí</td>
<td>Sí</td>
</tr>
<tr class="even">
<td>Estudios Pedagógicos</td>
<td>44</td>
<td>12,642</td>
<td>1241</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Journal of the Chilean Chemical Society</td>
<td>44</td>
<td>17,365</td>
<td>1838</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="even">
<td>Maderas-Cienc Tecnol</td>
<td>40</td>
<td>10,261</td>
<td>945</td>
<td>Sí</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Terapia Psicológica</td>
<td>39</td>
<td>6,845</td>
<td>471</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="even">
<td>Psykhe</td>
<td>35</td>
<td>6,655</td>
<td>885</td>
<td>Sí</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Chungara Revista de Antropología Chilena</td>
<td>35</td>
<td>8,353</td>
<td>1149</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="even">
<td>Polis (Santiago)</td>
<td>35</td>
<td>7,111</td>
<td>1042</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="odd">
<td>Revista de Biología Marina y Oceanografía</td>
<td>34</td>
<td>9,181</td>
<td>1087</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr class="even">
<td>Revista de Geografía Norte Grande</td>
<td>32</td>
<td>5,407</td>
<td>935</td>
<td>Sí</td>
<td>Sí</td>
</tr>
</tbody>
</table>
<p><strong>Oportunidades de mejora (alta productividad, baja visibilidad):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Revista</th>
<th>ISSN</th>
<th>Artículos Totales</th>
<th>Índice Visibilidad</th>
<th>Potencial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Revista Inclusiones</td>
<td>0719-4706</td>
<td>2,671</td>
<td>0.42</td>
<td>Alto</td>
</tr>
<tr class="even">
<td>Onomázein</td>
<td>0718-5758</td>
<td>1,081</td>
<td>0.78</td>
<td>Alto</td>
</tr>
<tr class="odd">
<td>Anales de Literatura Chilena</td>
<td>0717-6058</td>
<td>956</td>
<td>0.20</td>
<td>Alto</td>
</tr>
<tr class="even">
<td>REVISTA CUHSO</td>
<td>2452-610X</td>
<td>910</td>
<td>0.00</td>
<td>Muy Alto</td>
</tr>
<tr class="odd">
<td>Revista AIDIS</td>
<td>0718-378X</td>
<td>897</td>
<td>0.33</td>
<td>Alto</td>
</tr>
</tbody>
</table>
<p><strong>Revistas de mayor impacto individual (datos definitivos Script 13):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 22%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Revista</th>
<th>Institución</th>
<th>H-index</th>
<th>Citaciones</th>
<th>Acceso Abierto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>JOTMI</td>
<td>Independiente</td>
<td>51</td>
<td>13,607</td>
<td>Sí</td>
</tr>
<tr class="even">
<td>Journal Chilean Chemical Society</td>
<td>Sociedad Química</td>
<td>44</td>
<td>17,365</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Estudios Pedagógicos</td>
<td>U. Austral Chile</td>
<td>44</td>
<td>12,642</td>
<td>Sí</td>
</tr>
<tr class="even">
<td>Maderas-Cienc Tecnol</td>
<td>U. del Bío-Bío</td>
<td>40</td>
<td>10,261</td>
<td>Sí</td>
</tr>
<tr class="odd">
<td>Terapia Psicológica</td>
<td>Independiente</td>
<td>39</td>
<td>6,845</td>
<td>Sí</td>
</tr>
</tbody>
</table>
<p><strong>Correlaciones identificadas:</strong> - <strong>H-index vs visibilidad</strong>: 0.627 (correlación fuerte) - <strong>Productividad vs visibilidad</strong>: 0.075 (correlación débil) - <strong>Artículos OpenAlex vs citaciones</strong>: 0.562 (correlación moderada)</p>
</section>
<section id="implicaciones-para-estrategia-de-indexación" class="level4">
<h4 class="anchored" data-anchor-id="implicaciones-para-estrategia-de-indexación">3.4.4 Implicaciones para estrategia de indexación</h4>
<p><strong>Criterios de priorización actualizados (basados en datos definitivos Script 13):</strong> 1. <strong>Revistas de élite</strong> (H-index ≥40): JOTMI (51), Estudios Pedagógicos (44), Journal Chilean Chemical Society (44), Maderas-Cienc Tecnol (40) 2. <strong>Revistas consolidadas</strong> (H-index 30-39): Terapia Psicológica (39), grupo de H-index 35 (Psykhe, Chungara, Polis), y Revista Biología Marina (34) 3. <strong>Revistas emergentes</strong> (H-index 20-29): Potencial de crecimiento hacia élite 4. <strong>Priorización institucional</strong>: Diversidad institucional en el top 10, con representación de UC, UChile, UACh, UBB</p>
</section>
<section id="análisis-openalex-ampliado-para-revistas-chilenas-activas-resultados-definitivos" class="level4">
<h4 class="anchored" data-anchor-id="análisis-openalex-ampliado-para-revistas-chilenas-activas-resultados-definitivos">3.4.5 Análisis OpenAlex ampliado para revistas chilenas activas (RESULTADOS DEFINITIVOS)</h4>
<p>Se realizó un enriquecimiento específico de datos OpenAlex para las <strong>316 revistas chilenas activas</strong>, obteniendo información detallada sobre políticas de acceso abierto, métricas de impacto y características editoriales.</p>
<p><strong>Consideraciones Técnicas:</strong></p>
<p><strong>Limitación metodológica:</strong> De las 316 revistas activas, <strong>12 revistas (3.8%) fueron excluidas</strong> del análisis OpenAlex por carecer de ISSN válido, requisito indispensable para consultas en la API de OpenAlex.</p>
<p><strong>Revistas excluidas (sin ISSN):</strong> - Comunicaciones: una revista de geología andina - Boletín de la Universidad de Chile<br>
- MGC / Revista de Gestión Cultural - Historia 396 - Revista Bits de Ciencia - Revista de Estudios Históricos - Filosofía Juridica - Inferencias: Boletín de Bioestadística - Nutrición y Vida - Revista Estudiantil de Ensayos Monográficos - EMERGENCIAS: Cuaderno del Magíster en Comunicación Política - Mirada Hemisférica</p>
<p><strong>Dataset final:</strong> 304 revistas procesadas (96.2% de cobertura)</p>
<p><strong>Resultados de Indexación y Visibilidad:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrica</th>
<th>Valor</th>
<th>Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Revistas procesadas</strong></td>
<td>304</td>
<td>100%</td>
</tr>
<tr class="even">
<td><strong>Indexadas en OpenAlex</strong></td>
<td>259</td>
<td><strong>85.2%</strong></td>
</tr>
<tr class="odd">
<td><strong>No indexadas</strong></td>
<td>45</td>
<td>14.8%</td>
</tr>
<tr class="even">
<td><strong>Total artículos indexados</strong></td>
<td>120,646</td>
<td>-</td>
</tr>
<tr class="odd">
<td><strong>Total citaciones</strong></td>
<td>267,428</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><strong>Políticas de Acceso Abierto:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Categoría</th>
<th>Revistas</th>
<th>Porcentaje</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Completamente Open Access</strong></td>
<td>245</td>
<td><strong>94.6%</strong></td>
</tr>
<tr class="even">
<td><strong>Indexadas en DOAJ</strong></td>
<td>132</td>
<td><strong>51.0%</strong></td>
</tr>
<tr class="odd">
<td><strong>Con APC informado</strong></td>
<td>3</td>
<td>1.2%</td>
</tr>
<tr class="even">
<td><strong>Fuentes “Core” (CWTS)</strong></td>
<td>8</td>
<td><strong>3.1%</strong></td>
</tr>
</tbody>
</table>
<p><strong>Hallazgo destacado:</strong> El <strong>94.6%</strong> de las revistas chilenas indexadas en OpenAlex son completamente de acceso abierto, superando significativamente el promedio global.</p>
<p><strong>Métricas de Impacto:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicador</th>
<th>Promedio</th>
<th>Mediana</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>H-index</strong></td>
<td>9.1</td>
<td>6.0</td>
</tr>
<tr class="even">
<td><strong>i10-index</strong></td>
<td>26.3</td>
<td>12.0</td>
</tr>
<tr class="odd">
<td><strong>Índice de visibilidad</strong></td>
<td>2.8</td>
<td>1.2</td>
</tr>
<tr class="even">
<td><strong>APC promedio (USD)</strong></td>
<td>$693</td>
<td>-</td>
</tr>
</tbody>
</table>
<p><strong>Revistas de Mayor Impacto (Análisis definitivo Script 13):</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ranking</th>
<th>Revista</th>
<th>Visibilidad</th>
<th>H-index</th>
<th>Estado OA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Chungara Revista de Antropología Chilena</td>
<td>51.56</td>
<td>35</td>
<td>OA</td>
</tr>
<tr class="even">
<td>2</td>
<td>Gayana</td>
<td>37.42</td>
<td>27</td>
<td>OA + DOAJ</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Revista de Biología Marina y Oceanografía</td>
<td>33.26</td>
<td>34</td>
<td>OA</td>
</tr>
<tr class="even">
<td>4</td>
<td>Journal of the Chilean Chemical Society</td>
<td>31.18</td>
<td>44</td>
<td>OA</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Gayana Botanica</td>
<td>27.40</td>
<td>24</td>
<td>OA + DOAJ</td>
</tr>
</tbody>
</table>
<p><strong>Nota:</strong> Esta tabla refleja los resultados del análisis ampliado (Script 13) que debe utilizarse como referencia definitiva para el informe y presentaciones.</p>
<p><strong>Implicaciones Estratégicas:</strong></p>
<ol type="1">
<li><p><strong>Alta adopción de acceso abierto:</strong> El 94.6% de revistas indexadas son completamente OA, posicionando a Chile como líder regional.</p></li>
<li><p><strong>Oportunidad DOAJ:</strong> Solo el 51% está en DOAJ, representando potencial de mejora para 127 revistas.</p></li>
<li><p><strong>Concentración de impacto:</strong> Las top 5 revistas concentran el mayor impacto en ciencias naturales y químicas.</p></li>
<li><p><strong>Limitación técnica:</strong> 12 revistas requieren asignación de ISSN para mejorar su visibilidad internacional.</p></li>
</ol>
<p><strong>Dataset generado:</strong> <code>13_chile_openalex_ampliado.csv</code> (32 campos, 304 registros)</p>
</section>
</section>
<section id="análisis-de-crossref---revistas-chilenas-activas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-crossref---revistas-chilenas-activas">3.5 Análisis de Crossref - revistas chilenas activas</h3>
<section id="cobertura-en-crossref" class="level4">
<h4 class="anchored" data-anchor-id="cobertura-en-crossref">3.5.1 Cobertura en Crossref</h4>
<p>El análisis de la presencia de revistas chilenas activas en Crossref revela una cobertura significativa:</p>
<ul>
<li><strong>Total revistas analizadas:</strong> 316</li>
<li><strong>Revistas encontradas en Crossref:</strong> 256 (81.0%)</li>
<li><strong>Revistas no registradas:</strong> 60 (19.0%)</li>
</ul>
</section>
<section id="distribución-de-dois-registrados" class="level4">
<h4 class="anchored" data-anchor-id="distribución-de-dois-registrados">3.5.2 Distribución de DOIs registrados</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Tipo de DOI</th>
<th>Cantidad Total</th>
<th>Promedio por Revista</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DOIs Actuales</td>
<td>15,910</td>
<td>62.1</td>
</tr>
<tr class="even">
<td>DOIs Históricos</td>
<td>80,844</td>
<td>315.8</td>
</tr>
<tr class="odd">
<td><strong>Total DOIs</strong></td>
<td><strong>96,754</strong></td>
<td><strong>377.9</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="cobertura-de-metadatos" class="level4">
<h4 class="anchored" data-anchor-id="cobertura-de-metadatos">3.5.3 Cobertura de metadatos</h4>
<p><strong>Metadatos Actuales (Current):</strong></p>
<ul>
<li>Resúmenes: 76.3% | Muy buena cobertura</li>
<li>Verificación de similitud: 73.8% | Buena cobertura</li>
<li>Licencias: 51.5% | Mejorable</li>
<li>ORCIDs: 44.9% | Mejorable</li>
<li>ROR IDs: 18.2% | Baja cobertura</li>
<li>Afiliaciones: 8.6% | Muy baja cobertura</li>
<li>Referencias: 7.9% | Muy baja cobertura</li>
<li>Políticas de actualización: 0.0% | Sin implementar</li>
</ul>
<p><strong>Metadatos Históricos (Backfile):</strong> - Resúmenes: 42.8% - Licencias: 28.5% - ORCIDs: 15.8% - Referencias: 8.1% - Afiliaciones: 3.2%</p>
</section>
<section id="top-10-revistas-por-dois-en-crossref" class="level4">
<h4 class="anchored" data-anchor-id="top-10-revistas-por-dois-en-crossref">3.5.4 Top 10 revistas por DOIs en Crossref</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Posición</th>
<th>Revista</th>
<th>DOIs Totales</th>
<th>DOIs Actuales</th>
<th>DOIs Históricos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Atenea (Concepción)</td>
<td>10,350</td>
<td>90</td>
<td>10,260</td>
</tr>
<tr class="even">
<td>2</td>
<td>Anales de la Universidad de Chile</td>
<td>2,724</td>
<td>90</td>
<td>2,634</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Journal of the Chilean Chemical Society</td>
<td>1,806</td>
<td>73</td>
<td>1,733</td>
</tr>
<tr class="even">
<td>4</td>
<td>ARS MEDICA Revista de Ciencias Médicas</td>
<td>1,559</td>
<td>103</td>
<td>1,456</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Estudios Internacionales</td>
<td>1,548</td>
<td>42</td>
<td>1,506</td>
</tr>
<tr class="even">
<td>6</td>
<td>Proyecciones (Antofagasta)</td>
<td>1,519</td>
<td>302</td>
<td>1,217</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Revista de Derecho Público</td>
<td>1,334</td>
<td>23</td>
<td>1,311</td>
</tr>
<tr class="even">
<td>8</td>
<td>Bosque (Valdivia)</td>
<td>1,325</td>
<td>108</td>
<td>1,217</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Revista de derecho (Coquimbo)</td>
<td>1,252</td>
<td>166</td>
<td>1,086</td>
</tr>
<tr class="even">
<td>10</td>
<td>Estudios pedagógicos (Valdivia)</td>
<td>1,242</td>
<td>189</td>
<td>1,053</td>
</tr>
</tbody>
</table>
</section>
<section id="relaciones-de-versiones-y-preprints" class="level4">
<h4 class="anchored" data-anchor-id="relaciones-de-versiones-y-preprints">3.5.5 Relaciones de versiones y preprints</h4>
<p>El análisis de relaciones de versiones reveló que las revistas chilenas <strong>no utilizan funcionalidades avanzadas</strong> de Crossref: - Artículos con preprints: 0 - Artículos que son preprints: 0 - Artículos con versiones: 0 - Relaciones de reemplazo: 0 - Total relaciones de versión: 0</p>
</section>
<section id="observaciones-clave-crossref" class="level4">
<h4 class="anchored" data-anchor-id="observaciones-clave-crossref">3.5.6 Observaciones clave Crossref</h4>
<p><strong>Fortalezas:</strong> - Alta cobertura en Crossref (81.0%) - Buena cobertura de resúmenes y verificación de similitud - Volumen significativo de DOIs registrados (96,754 totales)</p>
<p><strong>Áreas de mejora:</strong> - Baja cobertura de afiliaciones y referencias - Ausencia de políticas de actualización - No aprovechamiento de relaciones de versiones/preprints - Cobertura mejorable de ORCIDs y licencias</p>
</section>
</section>
<section id="análisis-comparativo-cruzado-integración-de-tres-fuentes" class="level3">
<h3 class="anchored" data-anchor-id="análisis-comparativo-cruzado-integración-de-tres-fuentes">3.6 Análisis comparativo cruzado: integración de tres fuentes</h3>
<section id="metodología-de-integración-script-15" class="level4">
<h4 class="anchored" data-anchor-id="metodología-de-integración-script-15">3.6.1 Metodología de integración (Script 15)</h4>
<p>Se desarrolló un análisis comparativo cruzado que integra datos de <strong>tres fuentes principales</strong>: - <strong>Dialnet</strong>: Calidad editorial y errores de metadatos (95 revistas) - <strong>OpenAlex</strong>: Visibilidad académica e impacto (304 revistas) - <strong>Crossref</strong>: Infraestructura DOI y metadatos (316 revistas)</p>
<p><strong>Variables novedosas calculadas:</strong> - <strong>Madurez editorial</strong>: Combina DOIs históricos + calidad Dialnet - <strong>Brecha de visibilidad</strong>: Diferencia entre potencial (DOIs) y realidad (indexación) - <strong>Coherencia de metadatos</strong>: Consistencia entre fuentes Dialnet-Crossref - <strong>Potencial de indexación</strong>: Índice combinado de calidad + visibilidad + infraestructura</p>
</section>
<section id="segmentación-estratégica" class="level4">
<h4 class="anchored" data-anchor-id="segmentación-estratégica">3.6.2 Segmentación estratégica</h4>
<p>Se clasificaron las <strong>316 revistas</strong> en 5 segmentos estratégicos:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 7%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Segmento</th>
<th>Cantidad</th>
<th>%</th>
<th>Características</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Básico</strong></td>
<td>139</td>
<td>44.0%</td>
<td>Desarrollo integral necesario</td>
</tr>
<tr class="even">
<td><strong>Problema</strong></td>
<td>60</td>
<td>19.0%</td>
<td>Alta visibilidad, baja calidad editorial</td>
</tr>
<tr class="odd">
<td><strong>Oportunidad</strong></td>
<td>60</td>
<td>19.0%</td>
<td>Alta calidad, baja visibilidad</td>
</tr>
<tr class="even">
<td><strong>Veterana</strong></td>
<td>51</td>
<td>16.1%</td>
<td>Infraestructura madura, modernización necesaria</td>
</tr>
<tr class="odd">
<td><strong>Estrella</strong></td>
<td>6</td>
<td>1.9%</td>
<td>Liderazgo en los tres niveles</td>
</tr>
</tbody>
</table>
</section>
<section id="top-10-revistas-por-potencial-combinado" class="level4">
<h4 class="anchored" data-anchor-id="top-10-revistas-por-potencial-combinado">3.6.3 Top 10 revistas por potencial combinado</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 28%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Ranking</th>
<th>Revista</th>
<th>Potencial</th>
<th>Segmento</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Journal of technology management &amp; innovation</td>
<td>13.59</td>
<td>Problema</td>
</tr>
<tr class="even">
<td>2</td>
<td>Terapia psicológica</td>
<td>13.42</td>
<td>Problema</td>
</tr>
<tr class="odd">
<td>3</td>
<td>European Journal of Education and Psychology</td>
<td>13.13</td>
<td>Básico</td>
</tr>
<tr class="even">
<td>4</td>
<td>Maderas Ciencia y tecnología</td>
<td>13.00</td>
<td>Problema</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Estudios pedagógicos (Valdivia)</td>
<td>12.71</td>
<td>Problema</td>
</tr>
<tr class="even">
<td>6</td>
<td>Revista de biología marina y oceanografía</td>
<td>12.61</td>
<td>Básico</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Journal of the Chilean Chemical Society</td>
<td>12.57</td>
<td>Problema</td>
</tr>
<tr class="even">
<td>8</td>
<td>Revista latinoamericana de educación inclusiva</td>
<td>12.55</td>
<td>Problema</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Psykhe (Santiago)</td>
<td>12.48</td>
<td>Básico</td>
</tr>
<tr class="even">
<td>10</td>
<td>Estudios de economía</td>
<td>12.42</td>
<td>Problema</td>
</tr>
</tbody>
</table>
</section>
<section id="correlaciones-clave-identificadas" class="level4">
<h4 class="anchored" data-anchor-id="correlaciones-clave-identificadas">3.6.4 Correlaciones clave identificadas</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 32%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Variables</th>
<th>Correlación</th>
<th>Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>APC vs Completitud metadatos</strong></td>
<td>-1.000</td>
<td>Perfecta correlación negativa</td>
</tr>
<tr class="even">
<td><strong>APC vs Madurez editorial</strong></td>
<td>-0.998</td>
<td>Revistas con APC menos maduras</td>
</tr>
<tr class="odd">
<td><strong>APC vs Visibilidad</strong></td>
<td>+0.996</td>
<td>Revistas con APC más visibles</td>
</tr>
<tr class="even">
<td><strong>APC vs Total DOIs</strong></td>
<td>+0.984</td>
<td>Revistas con APC más DOIs</td>
</tr>
<tr class="odd">
<td><strong>H-index vs APC</strong></td>
<td>+0.965</td>
<td>Mayor impacto en revistas con APC</td>
</tr>
</tbody>
</table>
</section>
<section id="recomendaciones-por-segmento" class="level4">
<h4 class="anchored" data-anchor-id="recomendaciones-por-segmento">3.6.5 Recomendaciones por segmento</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Segmento</th>
<th>Recomendación Estratégica</th>
<th>Cantidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Estrella</strong></td>
<td>Mantener liderazgo, explorar indexación premium</td>
<td>6</td>
</tr>
<tr class="even">
<td><strong>Oportunidad</strong></td>
<td>Aumentar visibilidad, marketing académico</td>
<td>60</td>
</tr>
<tr class="odd">
<td><strong>Problema</strong></td>
<td>Mejorar calidad editorial, revisar procesos</td>
<td>60</td>
</tr>
<tr class="even">
<td><strong>Veterana</strong></td>
<td>Modernizar infraestructura, nuevos estándares</td>
<td>51</td>
</tr>
<tr class="odd">
<td><strong>Básico</strong></td>
<td>Desarrollo integral en los tres niveles</td>
<td>139</td>
</tr>
</tbody>
</table>
</section>
<section id="análisis-apc-vs-revistas-gratuitas-script-16" class="level4">
<h4 class="anchored" data-anchor-id="análisis-apc-vs-revistas-gratuitas-script-16">3.6.6 Análisis APC vs revistas gratuitas (Script 16)</h4>
<p><strong>Hallazgos Principales:</strong></p>
<p>El análisis revela que <strong>solo 3 revistas chilenas (0.9%)</strong> cobran Article Processing Charges (APC):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Revista</th>
<th>APC (USD)</th>
<th>H-index</th>
<th>Segmento</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Revista Inclusiones</strong></td>
<td>$80</td>
<td>16</td>
<td>Veterana</td>
</tr>
<tr class="even">
<td><strong>Gayana (Concepción)</strong></td>
<td>$1,000</td>
<td>27</td>
<td>Problema</td>
</tr>
<tr class="odd">
<td><strong>Gayana Botánica</strong></td>
<td>$1,000</td>
<td>24</td>
<td>Problema</td>
</tr>
</tbody>
</table>
<p><strong>Comparación de Métricas Clave:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Métrica</th>
<th>Con APC</th>
<th>Gratuitas</th>
<th>Diferencia</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Completitud Metadatos</strong></td>
<td>32.81</td>
<td>32.97</td>
<td>-0.5%</td>
</tr>
<tr class="even">
<td><strong>Visibilidad Académica</strong></td>
<td>2.72</td>
<td>0.97</td>
<td><strong>+181%</strong></td>
</tr>
<tr class="odd">
<td><strong>H-Index</strong></td>
<td>22.33</td>
<td>7.61</td>
<td><strong>+193%</strong></td>
</tr>
<tr class="even">
<td><strong>Total DOIs</strong></td>
<td>511.33</td>
<td>303.19</td>
<td><strong>+69%</strong></td>
</tr>
</tbody>
</table>
<p><strong>Distribución por Segmentos:</strong></p>
<ul>
<li><strong>Ninguna revista “Estrella”</strong> cobra APC</li>
<li><strong>Segmento “Problema”</strong>: 3.3% cobra APC (2/60)</li>
<li><strong>Segmento “Veterana”</strong>: 2.0% cobra APC (1/51)</li>
<li><strong>Segmentos “Básico” y “Oportunidad”</strong>: 0% cobra APC</li>
</ul>
<p><strong>Implicaciones Estratégicas:</strong></p>
<p><strong>Fortalezas del modelo chileno:</strong> - <strong>99.1% de revistas gratuitas</strong> promueve acceso abierto - <strong>Calidad editorial similar</strong> independiente del modelo de financiamiento - <strong>Diversidad de financiamiento</strong> (institucional, gubernamental)</p>
<p><strong>Oportunidades identificadas:</strong> - Las pocas revistas con APC muestran <strong>mayor impacto académico</strong> - Modelo híbrido podría beneficiar revistas de alto impacto - <strong>Financiamiento institucional</strong> mantiene acceso abierto</p>
<hr>
</section>
</section>
</section>
<section id="discusión" class="level2">
<h2 class="anchored" data-anchor-id="discusión">4. Discusión</h2>
<section id="validación-del-ecosistema-global" class="level3">
<h3 class="anchored" data-anchor-id="validación-del-ecosistema-global">4.1 Validación del ecosistema global</h3>
<p>La <strong>validación v6</strong> confirma el crecimiento acelerado del ecosistema OJS global, con <strong>86,282 instalaciones</strong> representando un aumento del <strong>28.4%</strong> respecto al beacon anterior. Este crecimiento es particularmente notable en:</p>
<ul>
<li><strong>Asia-Pacífico:</strong> Indonesia lidera con 23,045 instalaciones activas</li>
<li><strong>América Latina:</strong> 8,485 instalaciones confirman la región como hub de acceso abierto</li>
<li><strong>Diversificación geográfica:</strong> 154 países con instalaciones activas</li>
</ul>
</section>
<section id="caracterización-del-ecosistema-chileno-actualizada" class="level3">
<h3 class="anchored" data-anchor-id="caracterización-del-ecosistema-chileno-actualizada">4.2 Caracterización del ecosistema chileno actualizada</h3>
<section id="fortalezas-confirmadas-v6" class="level4">
<h4 class="anchored" data-anchor-id="fortalezas-confirmadas-v6">4.2.1 Fortalezas confirmadas v6</h4>
<ul>
<li><strong>Alta actividad editorial:</strong> 73.8% de instalaciones activas (vs 78.0% anterior)</li>
<li><strong>Crecimiento sostenido:</strong> +16.5% en publicaciones 2024</li>
<li><strong>Diversidad institucional:</strong> 181 instalaciones en “otras instituciones” (56.7%)</li>
<li><strong>Productividad destacada:</strong> Promedio 44.4 artículos por instalación</li>
</ul>
</section>
<section id="tendencias-identificadas" class="level4">
<h4 class="anchored" data-anchor-id="tendencias-identificadas">4.2.2 Tendencias identificadas</h4>
<ul>
<li><strong>Concentración en líderes:</strong> Universidad de Chile mantiene 21% del ecosistema</li>
<li><strong>Crecimiento diferenciado:</strong> Algunas instituciones decrecen mientras otras crecen</li>
<li><strong>Nuevas instalaciones:</strong> +36 instalaciones identificadas en v6</li>
</ul>
</section>
</section>
<section id="análisis-comparativo-cruzado-nuevas-perspectivas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-comparativo-cruzado-nuevas-perspectivas">4.3 Análisis comparativo cruzado: nuevas perspectivas</h3>
<section id="integración-exitosa-de-tres-fuentes" class="level4">
<h4 class="anchored" data-anchor-id="integración-exitosa-de-tres-fuentes">4.3.1 Integración exitosa de tres fuentes</h4>
<p>La <strong>metodología de análisis cruzado</strong> (Script 15) permite por primera vez una visión <strong>integral</strong> del ecosistema editorial chileno, combinando: - <strong>Calidad editorial</strong> (Dialnet): Errores y completitud de metadatos - <strong>Visibilidad académica</strong> (OpenAlex): Impacto y citaciones - <strong>Infraestructura técnica</strong> (Crossref): DOIs y metadatos estructurados</p>
</section>
<section id="segmentación-estratégica-validada" class="level4">
<h4 class="anchored" data-anchor-id="segmentación-estratégica-validada">4.3.2 Segmentación estratégica validada</h4>
<p>La clasificación en <strong>5 segmentos</strong> proporciona una <strong>hoja de ruta clara</strong>: - <strong>1.9% Estrellas</strong>: Liderazgo confirmado, indexación prioritaria - <strong>19% Oportunidades</strong>: Alto potencial, estrategias de visibilidad - <strong>19% Problemas</strong>: Revisión de procesos editoriales - <strong>44% Básicas</strong>: Desarrollo integral necesario</p>
</section>
<section id="modelo-de-financiamiento-sostenible" class="level4">
<h4 class="anchored" data-anchor-id="modelo-de-financiamiento-sostenible">4.3.3 Modelo de financiamiento sostenible</h4>
<p>El <strong>análisis APC</strong> (Script 16) confirma que Chile mantiene un <strong>modelo de acceso abierto robusto</strong>: - <strong>99.1% revistas gratuitas</strong> sin comprometer calidad - <strong>Financiamiento institucional</strong> como pilar del sistema - <strong>Impacto diferenciado</strong>: Las pocas revistas con APC muestran mayor visibilidad</p>
</section>
</section>
<section id="implicaciones-para-indexación-en-dialnet" class="level3">
<h3 class="anchored" data-anchor-id="implicaciones-para-indexación-en-dialnet">4.4 Implicaciones para indexación en Dialnet</h3>
<section id="optimización-del-proceso" class="level4">
<h4 class="anchored" data-anchor-id="optimización-del-proceso">4.4.1 Optimización del proceso</h4>
<ul>
<li><strong>225 URLs únicas</strong> (vs 208 anteriores) para evaluación</li>
<li><strong>Eliminación automática</strong> de 94 duplicados</li>
<li><strong>Cobertura mejorada:</strong> 81.5% de publicaciones 2024 representadas</li>
</ul>
</section>
<section id="estrategia-de-priorización-actualizada" class="level4">
<h4 class="anchored" data-anchor-id="estrategia-de-priorización-actualizada">4.4.2 Estrategia de priorización actualizada</h4>
<p>El <strong>análisis comparativo cruzado</strong> permite priorizar por <strong>múltiples criterios</strong>:</p>
<p><strong>Prioridad 1 - Revistas Estrella (6):</strong> - Liderazgo en calidad + visibilidad + infraestructura - Indexación inmediata recomendada</p>
<p><strong>Prioridad 2 - Oportunidades de Alto Impacto (60):</strong> - Alta calidad editorial, potencial de visibilidad - Estrategias de marketing académico</p>
<p><strong>Prioridad 3 - Revistas con APC (3):</strong> - Mayor impacto académico demostrado - Modelo de financiamiento sostenible</p>
<p><strong>Criterios de evaluación integrados:</strong> 1. <strong>Potencial combinado</strong> (Script 15) 2. <strong>Productividad 2024</strong> (Script 4) 3. <strong>Calidad editorial</strong> (Scripts 8-9) 4. <strong>Visibilidad académica</strong> (Scripts 10-12)</p>
</section>
</section>
<section id="contribución-al-acceso-abierto-regional" class="level3">
<h3 class="anchored" data-anchor-id="contribución-al-acceso-abierto-regional">4.5 Contribución al acceso abierto regional</h3>
<p>Los <strong>144,529 artículos históricos</strong> acumulados (vs 133,931 anteriores) posicionan a Chile como contribuyente significativo al ecosistema latinoamericano, con un <strong>crecimiento del 7.9%</strong> en el acervo histórico.</p>
</section>
<section id="limitaciones-y-consideraciones" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones-y-consideraciones">4.6 Limitaciones y consideraciones</h3>
<ol type="1">
<li><strong>Criterio temporal:</strong> Cambio de 2023 a 2024 puede afectar comparabilidad directa</li>
<li><strong>Cobertura beacon:</strong> Dependencia de instalaciones que mantienen beacon activo</li>
<li><strong>Variabilidad institucional:</strong> Algunas instituciones muestran decrecimiento</li>
</ol>
<hr>
</section>
</section>
<section id="limitaciones-del-estudio" class="level2">
<h2 class="anchored" data-anchor-id="limitaciones-del-estudio">5. Limitaciones del estudio</h2>
<section id="limitaciones-metodológicas" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones-metodológicas">5.1 Limitaciones metodológicas</h3>
<ul>
<li><strong>Dependencia del PKP Beacon:</strong> Solo incluye instalaciones con beacon activo</li>
<li><strong>Criterio temporal:</strong> Cambio de 2023 a 2024 afecta comparabilidad histórica</li>
<li><strong>Cobertura geográfica:</strong> Posible subrepresentación de instalaciones sin identificación clara de país</li>
</ul>
</section>
<section id="limitaciones-técnicas" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones-técnicas">5.2 Limitaciones técnicas</h3>
<ul>
<li><strong>Endpoints OAI:</strong> Variabilidad en configuración y disponibilidad</li>
<li><strong>Duplicados:</strong> Posibles instalaciones múltiples de la misma revista</li>
<li><strong>Datos faltantes:</strong> Instalaciones sin ISSN o metadatos incompletos</li>
</ul>
</section>
<section id="limitaciones-de-alcance" class="level3">
<h3 class="anchored" data-anchor-id="limitaciones-de-alcance">5.3 Limitaciones de alcance</h3>
<ul>
<li><strong>Evaluación Dialnet:</strong> Proceso manual limita escalabilidad</li>
<li><strong>Visibilidad académica:</strong> Análisis OpenAlex completado exitosamente</li>
<li><strong>Políticas de acceso abierto:</strong> Sherpa Romeo en transición (API restringida)</li>
<li><strong>Impacto editorial:</strong> No incluye métricas de citación o factor de impacto</li>
</ul>
<hr>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">6. Conclusiones</h2>
<section id="validación-del-ecosistema-robusto" class="level3">
<h3 class="anchored" data-anchor-id="validación-del-ecosistema-robusto">6.1 Validación del ecosistema robusto</h3>
<p>La <strong>validación v6</strong> confirma que Chile mantiene un ecosistema editorial académico <strong>robusto y en crecimiento</strong> con: - <strong>432 instalaciones OJS</strong> identificadas (+9.1% vs versión anterior) - <strong>319 instalaciones activas</strong> con criterio 2024 (73.8%) - <strong>14,162 publicaciones en 2024</strong> (+16.5% vs 2023)</p>
</section>
<section id="liderazgo-institucional-confirmado" class="level3">
<h3 class="anchored" data-anchor-id="liderazgo-institucional-confirmado">6.2 Liderazgo institucional confirmado</h3>
<p>La <strong>Universidad de Chile</strong> mantiene su posición dominante con: - <strong>67 instalaciones</strong> (21% del ecosistema) - <strong>3,338 publicaciones en 2024</strong> - <strong>Crecimiento de +1,646 publicaciones</strong></p>
</section>
<section id="crecimiento-sostenido-validado" class="level3">
<h3 class="anchored" data-anchor-id="crecimiento-sostenido-validado">6.3 Crecimiento sostenido validado</h3>
<p>El <strong>51.1% de instalaciones</strong> muestra crecimiento positivo, confirmando la vitalidad del sistema editorial chileno en el contexto global de acceso abierto.</p>
</section>
<section id="metodología-consolidada" class="level3">
<h3 class="anchored" data-anchor-id="metodología-consolidada">6.4 Metodología consolidada</h3>
<p>La <strong>validación cruzada v5-v6</strong> demuestra: - <strong>Consistencia metodológica:</strong> Resultados coherentes entre versiones - <strong>Actualización exitosa:</strong> Criterios 2024 reflejan estado actual - <strong>Escalabilidad:</strong> Procedimientos replicables para análisis futuros</p>
</section>
<section id="posicionamiento-global" class="level3">
<h3 class="anchored" data-anchor-id="posicionamiento-global">6.5 Posicionamiento global</h3>
<p>Chile se posiciona como <strong>actor relevante</strong> en el ecosistema latinoamericano de acceso abierto, contribuyendo significativamente a la democratización del conocimiento científico regional.</p>
</section>
</section>
<section id="agradecimientos" class="level2">
<h2 class="anchored" data-anchor-id="agradecimientos">Agradecimientos</h2>
<p>Al Public Knowledge Project (PKP) por mantener el sistema de beacon que hace posible este análisis. A la Universidad de La Rioja y el equipo de Dialnet por facilitar el acceso a su sistema de evaluación de revistas. A las instituciones chilenas que mantienen instalaciones OJS activas, contribuyendo al ecosistema de acceso abierto regional.</p>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-alperin2016peripheries" class="csl-entry" role="listitem">
Alperin, J. P., Stranack, K., &amp; Garnett, A. (2016). On the Peripheries of Scholarly Infrastructure: A Look at the Journals Using Open Journal Systems. <em>Proceedings of the 21st International Conference on Science and Technology Indicators</em>. <a href="https://summit.sfu.ca/_flysystem/fedora/sfu_migrate/16763/ojsstats2016.pdf">https://summit.sfu.ca/_flysystem/fedora/sfu_migrate/16763/ojsstats2016.pdf</a>
</div>
<div id="ref-chavarro2025open" class="csl-entry" role="listitem">
Chavarro, D., Alperin, J. P., &amp; Willinsky, J. (2025). On the open road to universal indexing: OpenAlex and Open Journal Systems. <em>Quantitative Science Studies</em>, <em>6</em>, 1039-1058. <a href="https://doi.org/10.1162/QSS.a.17">https://doi.org/10.1162/QSS.a.17</a>
</div>
<div id="ref-khanna2022recalibrating" class="csl-entry" role="listitem">
Khanna, S., Ball, J., Alperin, J. P., &amp; Willinsky, J. (2022). Recalibrating the scope of scholarly publishing: A modest step in a vast decolonization process. <em>Quantitative Science Studies</em>, <em>3</em>(4), 912-930. <a href="https://doi.org/10.1162/qss_a_00228">https://doi.org/10.1162/qss_a_00228</a>
</div>
<div id="ref-khanna2024details" class="csl-entry" role="listitem">
Khanna, S., Raoni, J., Smecher, A., Alperin, J. P., Ball, J., &amp; Willinsky, J. (2024). <em>Details of publications using software by the Public Knowledge Project</em>. Harvard Dataverse. <a href="https://doi.org/10.7910/DVN/OCZNVY">https://doi.org/10.7910/DVN/OCZNVY</a>
</div>
</div>
</section>
<section id="colaboraciones" class="level2">
<h2 class="anchored" data-anchor-id="colaboraciones">Colaboraciones</h2>
<p><strong>Geraldine Trujillo</strong> - Procesamiento y descarga manual de informes Dialnet - Evaluación sistemática de URLs en validador Nexus - Organización y carga de archivos HTML</p>
<p><strong>Claude (Anthropic)</strong> - Procesamiento y optimización de scripts de análisis - Apoyo en redacción y estructuración del informe - Asistencia técnica vía Claude Web y Amazon Q Developer</p>
<hr>
</section>
<section id="anexos" class="level2">
<h2 class="anchored" data-anchor-id="anexos">Anexos</h2>
<section id="anexo-a-diccionario-de-datos-del-pkp-beacon" class="level3">
<h3 class="anchored" data-anchor-id="anexo-a-diccionario-de-datos-del-pkp-beacon">Anexo A: Diccionario de datos del PKP Beacon</h3>
<section id="campos-descriptivos" class="level4">
<h4 class="anchored" data-anchor-id="campos-descriptivos">Campos descriptivos</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Ejemplo</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>application</code></td>
<td>OJS</td>
<td>Tipo de aplicación (OJS, OMP o OPS)</td>
</tr>
<tr class="even">
<td><code>version</code></td>
<td>3.2.1.4</td>
<td>Versión del software</td>
</tr>
<tr class="odd">
<td><code>country_consolidated</code></td>
<td>CL</td>
<td>País resuelto/final asignado</td>
</tr>
<tr class="even">
<td><code>set_spec</code></td>
<td>psykhe</td>
<td>Identificador de revista específica</td>
</tr>
<tr class="odd">
<td><code>context_name</code></td>
<td>Psykhe</td>
<td>Nombre completo de la revista</td>
</tr>
<tr class="even">
<td><code>issn</code></td>
<td>0718-2228</td>
<td>ISSN de la revista</td>
</tr>
</tbody>
</table>
</section>
<section id="campos-de-conteo-y-actividad" class="level4">
<h4 class="anchored" data-anchor-id="campos-de-conteo-y-actividad">Campos de conteo y actividad</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 31%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>Campo</th>
<th>Ejemplo</th>
<th>Descripción</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>total_record_count</code></td>
<td>872</td>
<td>Total artículos publicados históricos</td>
</tr>
<tr class="even">
<td><code>record_count_2023</code></td>
<td>41</td>
<td>Artículos publicados en 2023</td>
</tr>
<tr class="odd">
<td><code>last_completed_update</code></td>
<td>2024-10-11</td>
<td>Última sincronización</td>
</tr>
<tr class="even">
<td><code>unresponsive_endpoint</code></td>
<td>0</td>
<td>Estado de respuesta (0=activo, 1=inactivo)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="anexo-b-scripts-desarrollados" class="level3">
<h3 class="anchored" data-anchor-id="anexo-b-scripts-desarrollados">Anexo B: Scripts desarrollados</h3>
<section id="scripts-de-análisis-general" class="level4">
<h4 class="anchored" data-anchor-id="scripts-de-análisis-general">Scripts de análisis general</h4>
<ul>
<li><code>scripts/1_split_beacon.py</code>: Separación por aplicación</li>
<li><code>scripts/2_analisis_ojs_mundial.R</code>: Análisis global</li>
<li><code>scripts/visualize_network_enhanced.py</code>: Análisis de redes</li>
<li><code>scripts/visualize_interactive.py</code>: Dashboards interactivos</li>
</ul>
</section>
<section id="scripts-específicos-de-chile" class="level4">
<h4 class="anchored" data-anchor-id="scripts-específicos-de-chile">Scripts específicos de Chile</h4>
<ul>
<li><code>scripts/3_analisis_chile.R</code>: Análisis chileno completo</li>
<li><code>scripts/4_chile_juojs_filtrado.R</code>: Filtrado JUOJS (dataset principal)</li>
<li><code>scripts/5_generar_urls_dialnet.py</code>: Generación URLs Dialnet</li>
<li><code>scripts/6_find_missing_reports.py</code>: Verificación completitud informes Dialnet</li>
<li><code>scripts/7_comparar_urls_v5_v6.py</code>: Comparación cruzada v5-v6</li>
<li><code>scripts/8_procesar_informes_dialnet.py</code>: Procesamiento informes HTML Dialnet</li>
<li><code>scripts/9_analizar_tipos_errores.py</code>: Análisis de tipos de errores por gravedad</li>
<li><code>scripts/10_openalex.py</code>: Enriquecimiento con métricas de visibilidad OpenAlex</li>
<li><code>scripts/11_filtrar_chile_visibilidad.py</code>: Filtrado de visibilidad para revistas chilenas activas</li>
<li><code>scripts/12_analisis_estrategico_visibilidad.py</code>: Análisis estratégico y categorización por visibilidad</li>
</ul>
</section>
</section>
<section id="anexo-c-proceso-de-evaluación-en-dialnet" class="level3">
<h3 class="anchored" data-anchor-id="anexo-c-proceso-de-evaluación-en-dialnet">Anexo C: Proceso de evaluación en Dialnet</h3>
<section id="estado-actual" class="level4">
<h4 class="anchored" data-anchor-id="estado-actual">Estado actual</h4>
<p><strong>Proceso manual</strong> de envío de 246 URLs únicas de instalaciones chilenas a través del portal web de Dialnet para solicitud de informes de calidad.</p>
</section>
<section id="organización-de-informes-descargados" class="level4">
<h4 class="anchored" data-anchor-id="organización-de-informes-descargados">Organización de informes descargados</h4>
<p><strong>Nomenclatura de archivos:</strong> Los informes de Dialnet se descargan y renombran siguiendo el patrón del dominio extraído de la URL OAI: - Se mantiene el formato exacto del dominio (incluyendo <code>www</code> si está presente) - Se omite <code>www</code> si no aparece en la URL original - Formato: <code>[dominio].pdf</code> o <code>[dominio].html</code></p>
<p><strong>Ejemplos de nomenclatura:</strong> - <code>https://revistas.udec.cl/index.php/index/oai</code> → <code>revistas.udec.cl.pdf</code> - <code>https://www.estudiospublicos.cl/index.php/index/oai</code> → <code>www.estudiospublicos.cl.pdf</code> - <code>http://revistas.uach.cl/index.php/index/oai</code> → <code>revistas.uach.cl.pdf</code></p>
<p><strong>Estructura de carpetas:</strong></p>
<pre><code>dialnet/
├── revistas.udec.cl.pdf
├── www.estudiospublicos.cl.pdf
├── revistas.uach.cl.pdf
└── ...</code></pre>
</section>
<section id="registro-de-errores-del-sistema-nexus" class="level4">
<h4 class="anchored" data-anchor-id="registro-de-errores-del-sistema-nexus">Registro de errores del sistema Nexus</h4>
<p><strong>Metodología de registro:</strong> Cuando el sistema Nexus de Dialnet arroja errores durante la consulta, estos se registran en el archivo <code>visualizations/chile_oai_urls_limpio.csv</code> agregando una coma seguida del mensaje de error.</p>
<p><strong>Formato de registro:</strong></p>
<pre class="csv"><code>oai_url,error_message
https://revistas.udec.cl/index.php/index/oai,Error al consultar la configuración de la revista: Error al leer el XML
https://www.biotaxa.org/index.php/index/oai,La url no corresponde a una revista recolectable por OAI.</code></pre>
<p><strong>Tipos de errores identificados:</strong> 1. <strong>Error al leer el XML</strong>: Problemas de formato o accesibilidad del endpoint OAI 2. <strong>URL no recolectable</strong>: Instalaciones que no cumplen estándares OAI-PMH 3. <strong>Timeout de conexión</strong>: Instalaciones temporalmente inaccesibles 4. <strong>Configuración incorrecta</strong>: Problemas en la configuración del servidor OJS</p>
</section>
<section id="limitaciones-identificadas" class="level4">
<h4 class="anchored" data-anchor-id="limitaciones-identificadas">Limitaciones identificadas</h4>
<ul>
<li>No existe API para automatizar solicitudes de informes</li>
<li>Requiere evaluación manual por parte del equipo de Dialnet</li>
<li>Proceso individual por cada URL de instalación</li>
<li>Algunos endpoints OAI presentan problemas técnicos</li>
</ul>
</section>
<section id="alternativas-evaluadas" class="level4">
<h4 class="anchored" data-anchor-id="alternativas-evaluadas">Alternativas evaluadas</h4>
<ul>
<li>Contacto directo para procesamiento en lote</li>
<li>Priorización por índice de visibilidad</li>
<li>Automatización de formularios (descartada por términos de servicio)</li>
<li>Pre-validación técnica de endpoints OAI antes del envío</li>
</ul>
</section>
</section>
<section id="anexo-d-reproducibilidad" class="level3">
<h3 class="anchored" data-anchor-id="anexo-d-reproducibilidad">Anexo D: Reproducibilidad</h3>
<section id="requisitos-del-sistema" class="level4">
<h4 class="anchored" data-anchor-id="requisitos-del-sistema">Requisitos del sistema</h4>
<ul>
<li>R 4.0+ con librerías: dplyr, ggplot2, readr, stringr</li>
<li>Python 3.8+ con librerías: pandas, requests, urllib</li>
<li>Sistema operativo: Linux/macOS (scripts optimizados para bash)</li>
</ul>
</section>
<section id="repositorio-de-código" class="level4">
<h4 class="anchored" data-anchor-id="repositorio-de-código">Repositorio de código</h4>
<ul>
<li><strong>Ubicación:</strong> <code>/scripts/</code> y <code>/scripts_v6/</code></li>
<li><strong>Orden de ejecución:</strong> Numeración secuencial (1-7)</li>
<li><strong>Datos de entrada:</strong> <code>beacon.csv</code> (v5) y <code>beacon_v6_clean.csv</code> (v6)</li>
<li><strong>Datos de salida:</strong> <code>/visualizations/</code> y <code>/visualizations_v6/</code></li>
</ul>
</section>
<section id="estructura-de-archivos-generados" class="level4">
<h4 class="anchored" data-anchor-id="estructura-de-archivos-generados">Estructura de archivos generados</h4>
<pre><code>OJSinTheWorld/Chile/
├── beacon.csv                    # Dataset v5 original
├── beacon_v6_clean.csv          # Dataset v6 limpiado
├── beacon_ojs.csv               # OJS filtrado v5
├── beacon_v6_ojs.csv           # OJS filtrado v6
├── scripts/
│   ├── 1_split_beacon.py
│   ├── 2_analisis_ojs_mundial.R
│   ├── 3_analisis_chile.R
│   ├── 4_chile_juojs_filtrado.R
│   ├── 5_generar_urls_dialnet.py
│   ├── 6_find_missing_reports.py
│   ├── 7_comparar_urls_v5_v6.py
│   ├── 8_procesar_informes_dialnet.py
│   └── 9_analizar_tipos_errores.py
├── scripts_v6/
│   ├── 1_split_beacon_v6.py
│   ├── 2_analisis_mundial_v6.R
│   ├── 3_analisis_chile_v6.R
│   ├── 4_chile_juojs_filtrado_v6.R
│   ├── 5_generar_urls_dialnet_v6.py
│   └── 6_tablas_chile_v6.R
├── visualizations/              # Resultados v5
│   ├── chile_todas_instalaciones.csv
│   ├── chile_juojs_activas.csv
│   ├── chile_oai_urls_limpio.csv
│   └── dialnet_informes_procesados.csv
├── visualizations_v6/           # Resultados v6
│   ├── chile_todas_instalaciones_v6.csv
│   ├── chile_juojs_activas_v6.csv
│   └── chile_oai_urls_limpio_v6.csv
└── dialnet/                     # Informes descargados
    ├── revistas.udec.cl.pdf
    ├── www.estudiospublicos.cl.pdf
    └── ...</code></pre>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Volver arriba</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reutilización</h2><div class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by/4.0/deed.es">CC BY 4.0</a></div></div></section><section class="quarto-appendix-contents" id="quarto-copyright"><h2 class="anchored quarto-appendix-heading">Derechos de autor</h2><div class="quarto-appendix-contents"><div>Patricio Iván Pantaleo</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/patricio\.pantaleo\.ar\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>